import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { NextRequest } from 'next/server'
const mock = vi.hoisted(() => ({ auth: vi.fn(), subscription: vi.fn(), process: vi.fn(), scan: vi.fn(), regression: vi.fn(), alert: vi.fn(), pdf: vi.fn(), db: { checkoutQuote: { findFirst: vi.fn() }, assuranceReport: { findFirst: vi.fn(), delete: vi.fn() }, assuranceDomain: { findFirst: vi.fn() } } }))
vi.mock('@/lib/auth', () => ({ requireAuth: mock.auth }))
vi.mock('@/lib/prisma', () => ({ prisma: mock.db }))
vi.mock('@/lib/assurance/billing', () => ({ getActiveAssuranceSubscription: mock.subscription, processAssuranceWebhookPayment: mock.process }))
vi.mock('@/lib/assurance/scanner', () => ({ triggerManualScan: mock.scan }))
vi.mock('@/lib/assurance/trends', () => ({ detectRegression: mock.regression, createAlert: mock.alert }))
vi.mock('@/lib/assurance/report-generator', () => ({ generateReportPDF: mock.pdf }))
import { POST as webhook } from './webhook/route'
import { POST as reconcile } from './reconcile/route'
import { GET as getReport, DELETE as deleteReport } from './reports/[id]/route'
import { GET as getPdf } from './reports/[id]/pdf/route'
import { POST as scan } from './domains/[id]/scan/route'
const req = (body: unknown = {}) => new NextRequest('https://app.example.test/api/assurance', { method: 'POST', body: JSON.stringify(body) })
const params = { params: Promise.resolve({ id: 'item1' }) }
const subscription = { id: 'as1', userId: 'u1', tier: 'BASIC', status: 'active', billingCycle: 'monthly' }
const report = (overrides = {}) => ({ id: 'item1', domainId: 'd1', scanId: 's1', language: 'nl', pdfUrl: '/placeholder', createdAt: new Date('2026-09-06Z'), domain: { id: 'd1', domain: 'example.test', label: null }, ...overrides })
beforeEach(() => { vi.resetAllMocks(); vi.spyOn(console, 'log').mockImplementation(() => {}); vi.spyOn(console, 'warn').mockImplementation(() => {}); vi.spyOn(console, 'error').mockImplementation(() => {}); mock.auth.mockResolvedValue({ id: 'u1' }); mock.subscription.mockResolvedValue(subscription); mock.process.mockResolvedValue(subscription); mock.db.checkoutQuote.findFirst.mockResolvedValue(null); mock.db.assuranceReport.findFirst.mockResolvedValue(report()); mock.pdf.mockResolvedValue(Buffer.from('%PDF')); mock.db.assuranceDomain.findFirst.mockResolvedValue({ id: 'item1', active: true, domain: 'https://example.test' }); mock.scan.mockResolvedValue({ id: 'ascan1', scanId: 'scan1', score: 91, issuesCount: 2 }); mock.regression.mockResolvedValue({ detected: false }) })
afterEach(() => vi.restoreAllMocks())

it.each(['', 'other=value', 'id=fake', 'id=tr_bad%2Fid'])('acknowledges dashboard pings without processing arbitrary IDs %s', async body => { const response = await webhook(new NextRequest('https://app.example.test/api/assurance/webhook', { method: 'POST', body })); expect(await response.json()).toEqual({ success: true, ping: true }); expect(mock.process).not.toHaveBeenCalled() })
it('parses real form-encoded webhook IDs and delegates provider verification', async () => { const response = await webhook(new NextRequest('https://app.example.test/api/assurance/webhook', { method: 'POST', body: 'id=tr_ABC123', headers: { 'Content-Type': 'application/x-www-form-urlencoded' } })); expect(await response.json()).toEqual({ success: true }); expect(mock.process).toHaveBeenCalledWith('tr_ABC123') })
it.each([new Error('provider down'), { status: 422, title: 'invalid' }])('does not claim webhook processing success when it throws', async error => { mock.process.mockRejectedValue(error); const response = await webhook(new NextRequest('https://app.example.test/api/assurance/webhook', { method: 'POST', body: 'id=tr_ABC123' })); expect(await response.json()).toEqual({ success: false }) })
it('requires authentication before reconciliation', async () => { mock.auth.mockRejectedValue(new Error('Authentication required')); expect((await reconcile(req())).status).toBe(401); expect(mock.process).not.toHaveBeenCalled() })
it('preserves the already-active fast path and never processes caller-supplied foreign IDs', async () => { expect(await (await reconcile(req({ paymentId: 'tr_OTHER' }))).json()).toMatchObject({ ok: true, alreadyActive: true, subscription: { id: 'as1' } }); expect(mock.process).not.toHaveBeenCalled(); expect(mock.db.checkoutQuote.findFirst).not.toHaveBeenCalled() })
it('rejects an explicit payment ID without a quote owned by the session user', async () => { mock.subscription.mockResolvedValue(null); const response = await reconcile(req({ paymentId: 'tr_OTHER' })); expect(response.status).toBe(404); expect(mock.db.checkoutQuote.findFirst).toHaveBeenCalledWith({ where: { userId: 'u1', product: 'assurance', molliePaymentId: 'tr_OTHER' }, select: { id: true } }); expect(mock.process).not.toHaveBeenCalled(); expect(await response.json()).not.toHaveProperty('subscription') })
it('reconciles an explicitly owned payment', async () => { mock.subscription.mockResolvedValue(null); mock.db.checkoutQuote.findFirst.mockResolvedValue({ id: 'q1' }); expect(await (await reconcile(req({ paymentId: 'tr_OWNED' }))).json()).toMatchObject({ ok: true, reconciled: true, subscription: { id: 'as1' } }); expect(mock.process).toHaveBeenCalledWith('tr_OWNED') })
it.each([{}, { paymentId: 'invalid' }])('looks up the latest owned assurance quote for missing/invalid references %j', async body => { mock.subscription.mockResolvedValue(null); mock.db.checkoutQuote.findFirst.mockResolvedValue({ molliePaymentId: 'tr_OWNED' }); await reconcile(req(body)); expect(mock.db.checkoutQuote.findFirst).toHaveBeenCalledWith({ where: { userId: 'u1', product: 'assurance' }, orderBy: { createdAt: 'desc' }, select: { molliePaymentId: true } }); expect(mock.process).toHaveBeenCalledWith('tr_OWNED') })
it('accepts an empty body and explains when no pending quote exists', async () => { mock.subscription.mockResolvedValue(null); const response = await reconcile(new NextRequest('https://app.example.test/api/assurance/reconcile', { method: 'POST' })); expect(response.status).toBe(404); expect(mock.process).not.toHaveBeenCalled() })
it('returns retryable pending-state details when payment is not paid yet', async () => { mock.subscription.mockResolvedValue(null); mock.db.checkoutQuote.findFirst.mockResolvedValue({ molliePaymentId: 'tr_OWNED' }); mock.process.mockResolvedValue(null); const response = await reconcile(req()); expect(response.status).toBe(409); expect(await response.json()).toMatchObject({ error: 'PAYMENT_NOT_PAID' }) })
it.each([new Error('db down'), { statusCode: 500 }])('contains reconciliation errors', async error => { mock.subscription.mockRejectedValue(error); expect((await reconcile(req())).status).toBe(500) })

const reportHandlers = [getReport, deleteReport, getPdf]
it.each(reportHandlers)('blocks report access without subscription ownership', async handler => { mock.subscription.mockResolvedValueOnce(null); expect((await handler(req(), params)).status).toBe(403); mock.db.assuranceReport.findFirst.mockResolvedValue(null); expect((await handler(req(), params)).status).toBe(404); expect(mock.pdf).not.toHaveBeenCalled(); expect(mock.db.assuranceReport.delete).not.toHaveBeenCalled() })
it('returns report details using a scoped lookup and optional display label', async () => { expect(await (await getReport(req(), params)).json()).toMatchObject({ id: 'item1', domain: { name: 'example.test' } }); mock.db.assuranceReport.findFirst.mockResolvedValue(report({ domain: { id: 'd1', domain: 'example.test', label: 'Main' } })); expect(await (await getReport(req(), params)).json()).toMatchObject({ domain: { name: 'Main' } }); expect(mock.db.assuranceReport.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'item1', domain: { subscriptionId: 'as1' } } })) })
it('deletes only the verified report', async () => { expect((await deleteReport(req(), params)).status).toBe(200); expect(mock.db.assuranceReport.delete).toHaveBeenCalledWith({ where: { id: 'item1' } }) })
it('redirects to stored HTTPS PDFs after ownership verification', async () => { mock.db.assuranceReport.findFirst.mockResolvedValue(report({ pdfUrl: 'https://storage.example.test/invoice.pdf' })); const response = await getPdf(req(), params); expect(response.status).toBe(307); expect(response.headers.get('Location')).toBe('https://storage.example.test/invoice.pdf'); expect(mock.pdf).not.toHaveBeenCalled() })
it('serves on-demand PDF bytes with private non-cacheable response headers', async () => { const response = await getPdf(req(), params); expect(response.status).toBe(200); expect(response.headers.get('Content-Type')).toBe('application/pdf'); expect(response.headers.get('Cache-Control')).toBe('no-store'); expect(response.headers.get('Content-Length')).toBe('4'); expect(await response.text()).toBe('%PDF'); expect(mock.pdf).toHaveBeenCalledWith({ domainId: 'd1', scanId: 's1', language: 'nl' }) })
it.each(reportHandlers)('contains report lookup failures', async handler => { mock.db.assuranceReport.findFirst.mockRejectedValue(new Error('db failed')); expect((await handler(req(), params)).status).toBe(500) })
it('requires active subscription and domain before manual scans', async () => { mock.subscription.mockResolvedValueOnce(null); expect((await scan(req(), params)).status).toBe(403); mock.db.assuranceDomain.findFirst.mockResolvedValueOnce(null).mockResolvedValueOnce({ active: false }); expect((await scan(req(), params)).status).toBe(404); expect((await scan(req(), params)).status).toBe(400); expect(mock.scan).not.toHaveBeenCalled() })
it('returns a non-regressing scan without creating alerts', async () => { expect(await (await scan(req(), params)).json()).toMatchObject({ success: true, scan: { id: 'ascan1', score: 91 }, regression: null }); expect(mock.scan).toHaveBeenCalledWith('item1'); expect(mock.alert).not.toHaveBeenCalled() })
it('creates a linked alert only for detected, typed regressions', async () => { mock.regression.mockResolvedValue({ detected: true, type: 'SCORE_DROP', severity: 'HIGH', message: 'Score dropped', currentScore: 70, previousScore: 91, threshold: 90 }); expect((await scan(req(), params)).status).toBe(200); expect(mock.alert).toHaveBeenCalledWith({ domainId: 'item1', type: 'SCORE_DROP', severity: 'HIGH', title: 'Score dropped', message: 'Score dropped', currentScore: 70, previousScore: 91, threshold: 90, scanId: 'scan1' }) })
it('does not create an alert when the regression detector supplies no type', async () => { mock.regression.mockResolvedValue({ detected: true, type: null }); await scan(req(), params); expect(mock.alert).not.toHaveBeenCalled() })
it.each([new Error('scanner unavailable'), 'scanner unavailable'])('contains scanner failures and creates no alert', async error => { mock.scan.mockRejectedValue(error); expect((await scan(req(), params)).status).toBe(500); expect(mock.alert).not.toHaveBeenCalled() })
