import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import { NextRequest } from 'next/server'
const mock = vi.hoisted(() => ({
  auth: vi.fn(), subscription: vi.fn(), cancel: vi.fn(), change: vi.fn(), checkout: vi.fn(), ssrf: vi.fn(), stats: vi.fn(), generateReport: vi.fn(),
  db: {
    billingProfile: { findUnique: vi.fn() }, assuranceDomain: { findMany: vi.fn(), findFirst: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn() },
    assuranceAlert: { findMany: vi.fn(), findFirst: vi.fn(), count: vi.fn(), update: vi.fn(), delete: vi.fn() }, assuranceReport: { findMany: vi.fn(), count: vi.fn(), findUnique: vi.fn() }, assuranceScan: { findFirst: vi.fn() },
  },
}))
vi.mock('@/lib/auth', () => ({ requireAuth: mock.auth }))
vi.mock('@/lib/prisma', () => ({ prisma: mock.db }))
vi.mock('@/lib/assurance/billing', () => ({ getActiveAssuranceSubscription: mock.subscription, cancelAssuranceSubscription: mock.cancel, changeAssuranceTier: mock.change, createAssuranceCheckoutPayment: mock.checkout }))
vi.mock('@/lib/security/ssrf-guard', () => ({ assertPublicHttpUrl: mock.ssrf }))
vi.mock('@/lib/assurance/trends', () => ({ getDomainStatistics: mock.stats }))
vi.mock('@/lib/assurance/report-generator', () => ({ generateAndStoreReport: mock.generateReport }))
import * as subscriptions from './subscription/route'
import { POST as subscribe } from './subscribe/route'
import * as domains from './domains/route'
import * as domain from './domains/[id]/route'
import { GET as listAlerts } from './alerts/route'
import * as alert from './alerts/[id]/route'
import * as reports from './reports/route'
const req = (body: unknown = {}, method = 'POST', query = '') => new NextRequest(`https://app.example.test/api/assurance${query}`, { method, ...(method !== 'GET' ? { body: JSON.stringify(body) } : {}) })
const params = { params: Promise.resolve({ id: 'item1' }) }
const sub = (overrides = {}) => ({ id: 'as1', tier: 'BASIC', status: 'active', billingCycle: 'monthly', pricePerMonth: 9.99, totalPrice: 9.99, domains: [], ...overrides })
const domainData = (overrides = {}) => ({ id: 'item1', domain: 'https://example.test', label: 'Example', language: 'nl', scans: [], alerts: [], reports: [], _count: { scans: 0, alerts: 0, reports: 0 }, ...overrides })
const alertData = (overrides = {}) => ({ id: 'item1', resolved: false, domain: { id: 'd1', domain: 'https://example.test', label: null }, ...overrides })
beforeEach(() => {
  vi.resetAllMocks(); vi.spyOn(console, 'log').mockImplementation(() => {}); vi.spyOn(console, 'warn').mockImplementation(() => {}); vi.spyOn(console, 'error').mockImplementation(() => {})
  mock.auth.mockResolvedValue({ id: 'u1', email: 'user@example.test' }); mock.subscription.mockResolvedValue(sub()); mock.cancel.mockResolvedValue({ id: 'as1', status: 'canceled' }); mock.change.mockResolvedValue(sub({ tier: 'PRO', pricePerMonth: 24.99, totalPrice: 24.99 })); mock.checkout.mockResolvedValue({ id: 'tr1', getCheckoutUrl: () => 'https://checkout.example.test/tr1' }); mock.db.billingProfile.findUnique.mockResolvedValue(null); mock.ssrf.mockResolvedValue({ ok: true, url: new URL('https://example.test/path?q=1') }); mock.db.assuranceDomain.count.mockResolvedValue(0); mock.db.assuranceDomain.findFirst.mockResolvedValue(null); mock.db.assuranceDomain.findMany.mockResolvedValue([]); mock.db.assuranceDomain.create.mockImplementation(({ data }) => ({ id: 'item1', ...data })); mock.db.assuranceDomain.update.mockImplementation(({ data }) => ({ ...domainData(), ...data })); mock.db.assuranceAlert.findMany.mockResolvedValue([]); mock.db.assuranceAlert.count.mockResolvedValue(0); mock.db.assuranceAlert.findFirst.mockResolvedValue(alertData()); mock.db.assuranceAlert.update.mockImplementation(({ data }) => ({ id: 'item1', ...data })); mock.db.assuranceReport.findMany.mockResolvedValue([]); mock.db.assuranceReport.count.mockResolvedValue(0); mock.generateReport.mockResolvedValue({ reportId: 'r1' }); mock.db.assuranceReport.findUnique.mockResolvedValue({ id: 'r1', pdfUrl: '/pdf', language: 'nl', score: 92, threshold: 90 }); mock.db.assuranceScan.findFirst.mockResolvedValue({ id: 'scan1' }); mock.stats.mockResolvedValue({ averageScore: 92 })
})
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); vi.useRealTimers() })

describe('Assurance checkout and subscription', () => {
  it('denies unauthenticated checkout without creating a payment', async () => { mock.auth.mockRejectedValue(new Error('no session')); const response = await subscribe(req({ tier: 'BASIC' })); expect(response.status).toBe(401); expect(await response.json()).toMatchObject({ code: 'AUTH_REQUIRED' }); expect(mock.checkout).not.toHaveBeenCalled() })
  it('reports malformed JSON distinctly', async () => { const response = await subscribe(new NextRequest('https://app.example.test/api/assurance/subscribe', { method: 'POST', body: '{invalid' })); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: 'INVALID_BODY' }) })
  it.each([[{}, 'INVALID_TIER'], [{ tier: 'unknown' }, 'INVALID_TIER'], [{ tier: 'BASIC', billingCycle: 'daily' }, 'INVALID_BILLING_CYCLE']])('validates checkout body %j', async (body, code) => { expect(await (await subscribe(req(body))).json()).toMatchObject({ ok: false, code }); expect(mock.checkout).not.toHaveBeenCalled() })
  it('fails without configured payment service', async () => { vi.stubEnv('MOLLIE_API_KEY', ''); expect(await (await subscribe(req({ tier: 'BASIC' }))).json()).toMatchObject({ code: 'CONFIG_MISSING_ENV' }); expect(mock.checkout).not.toHaveBeenCalled() })
  it('uses authenticated identity and persisted tax evidence for checkout', async () => { mock.db.billingProfile.findUnique.mockResolvedValue({ countryCode: 'DE', billingType: 'business', vatValid: true, vatId: 'DE123' }); const response = await subscribe(req({ tier: 'PRO', billingCycle: 'annual', userId: 'other' })); expect(response.status).toBe(200); expect(await response.json()).toMatchObject({ ok: true, paymentId: 'tr1' }); expect(mock.checkout).toHaveBeenCalledWith(expect.objectContaining({ userId: 'u1', email: 'user@example.test', tier: 'PRO', billingCycle: 'annual', taxDecision: expect.objectContaining({ vatRate: 0, regime: 'EU_REVERSE_CHARGE' }) })) })
  it('uses safe defaults if profile lookup or public app URL is unavailable', async () => { vi.stubEnv('NEXT_PUBLIC_APP_URL', ''); mock.db.billingProfile.findUnique.mockRejectedValue(new Error('db down')); expect((await subscribe(req({ tier: 'BASIC' }))).status).toBe(200); expect(mock.checkout).toHaveBeenCalledWith(expect.objectContaining({ billingCycle: 'monthly', taxDecision: undefined })) })
  it('handles a provider payment without checkout URL', async () => { mock.checkout.mockResolvedValue({ id: 'tr1', getCheckoutUrl: () => null }); const response = await subscribe(req({ tier: 'BASIC' })); expect(response.status).toBe(502); expect(await response.json()).toMatchObject({ code: 'PROVIDER_NO_CHECKOUT_URL' }) })
  it.each([[new Error('MOLLIE_API_KEY missing'), 500, 'CONFIG_MISSING_ENV'], [new Error('environment variable missing'), 500, 'CONFIG_MISSING_ENV'], [new Error('provider failed'), 502, 'PROVIDER_ERROR'], ['provider failed', 502, 'PROVIDER_ERROR']])('maps provider failures without exposing raw details', async (error, status, code) => { mock.checkout.mockRejectedValue(error); const response = await subscribe(req({ tier: 'BASIC' })); expect(response.status).toBe(status); expect(await response.json()).toMatchObject({ code, requestId: expect.stringMatching(/^req_/) }) })
  it('shows empty subscription state and formats active prices as strings', async () => { mock.subscription.mockResolvedValueOnce(null); expect(await (await subscriptions.GET()).json()).toEqual({ hasSubscription: false, subscription: null }); expect(await (await subscriptions.GET()).json()).toMatchObject({ hasSubscription: true, subscription: { pricePerMonth: '9.99', totalPrice: '9.99' }, usage: { domains: 0, maxDomains: 1 } }) })
  it('protects subscription reads and handles lookup failures', async () => { mock.auth.mockRejectedValueOnce(new Error('Authentication required')).mockRejectedValueOnce(new Error('db failed')); expect((await subscriptions.GET()).status).toBe(401); expect((await subscriptions.GET()).status).toBe(500) })
  it('validates tier changes and requires an existing subscription', async () => { expect((await subscriptions.PATCH(req({ tier: 'INVALID' }))).status).toBe(400); mock.subscription.mockResolvedValue(null); expect((await subscriptions.PATCH(req({ tier: 'PRO' }))).status).toBe(404); expect((await subscriptions.DELETE()).status).toBe(404) })
  it('changes only the session’s subscription and preserves billing cycle', async () => { expect((await subscriptions.PATCH(req({ tier: 'PRO', billingCycle: 'annual', subscriptionId: 'other' }))).status).toBe(200); expect(mock.change).toHaveBeenCalledWith({ subscriptionId: 'as1', newTier: 'PRO', billingCycle: 'annual' }); expect((await subscriptions.DELETE()).status).toBe(200); expect(mock.cancel).toHaveBeenCalledWith('as1') })
  it('contains subscription mutation provider errors', async () => { mock.change.mockRejectedValue(new Error('provider failed')); mock.cancel.mockRejectedValue(new Error('provider failed')); expect((await subscriptions.PATCH(req({ tier: 'PRO' }))).status).toBe(500); expect((await subscriptions.DELETE()).status).toBe(500) })
})

describe('domain creation and validation', () => {
  it('requires a subscription before storing domains', async () => { mock.subscription.mockResolvedValue(null); expect((await domains.POST(req({ domain: 'https://example.test' }))).status).toBe(403); expect(await (await domains.GET()).json()).toEqual({ domains: [], hasSubscription: false }); expect(mock.db.assuranceDomain.create).not.toHaveBeenCalled() })
  it.each([undefined, '', 123])('rejects missing or invalid domain %s', async value => { expect((await domains.POST(req({ domain: value }))).status).toBe(400); expect(mock.ssrf).not.toHaveBeenCalled() })
  it('rejects SSRF targets before persistence or scheduling', async () => { mock.ssrf.mockResolvedValue({ ok: false, error: 'Private target blocked' }); expect(await (await domains.POST(req({ domain: 'http://127.0.0.1' }))).json()).toEqual({ error: 'Private target blocked' }); expect(mock.db.assuranceDomain.create).not.toHaveBeenCalled() })
  it.each([['BASIC', 1], ['PRO', 5]] as const)('enforces %s domain capacity', async (tier, count) => { mock.subscription.mockResolvedValue(sub({ tier })); mock.db.assuranceDomain.count.mockResolvedValue(count); expect((await domains.POST(req({ domain: 'https://example.test' }))).status).toBe(403); expect(mock.db.assuranceDomain.create).not.toHaveBeenCalled() })
  it.each([{ scoreThreshold: 89 }, { scanFrequency: 'DAILY' }, { emailRecipients: 'invalid' }, { emailRecipients: Array(6).fill('x@example.test') }, { emailRecipients: ['invalid'] }, { language: 'invalid' }])('rejects invalid domain settings %j', async options => { expect((await domains.POST(req({ domain: 'https://example.test', ...options }))).status).toBe(400); expect(mock.db.assuranceDomain.create).not.toHaveBeenCalled() })
  it('enforces the Public Sector threshold range', async () => { mock.subscription.mockResolvedValue(sub({ tier: 'PUBLIC_SECTOR' })); expect(await (await domains.POST(req({ domain: 'https://example.test', scoreThreshold: 59 }))).json()).toEqual({ error: 'Threshold must be between 60 and 100' }) })
  it('deduplicates the validated origin within the session’s subscription', async () => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); expect((await domains.POST(req({ domain: 'https://example.test/path?x=1' }))).status).toBe(409); expect(mock.db.assuranceDomain.findFirst).toHaveBeenCalledWith({ where: { subscriptionId: 'as1', domain: 'https://example.test' } }) })
  it('stores only the validated origin and applies safe weekly defaults', async () => { vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 8, 6, 12)); const response = await domains.POST(req({ domain: 'https://example.test/path?x=1' })); expect(response.status).toBe(200); expect(mock.db.assuranceDomain.create).toHaveBeenCalledWith({ data: expect.objectContaining({ subscriptionId: 'as1', domain: 'https://example.test', scoreThreshold: 90, scanFrequency: 'WEEKLY', language: 'en', dayOfWeek: 1, timeOfDay: '09:00', nextRunAt: new Date(2026, 8, 7, 9) }) }) })
  it.each([['WEEKLY', 14], ['BIWEEKLY', 21]] as const)('schedules %s after today’s target time has passed', async (scanFrequency, day) => { vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 8, 7, 12)); await domains.POST(req({ domain: 'https://example.test', scanFrequency, emailRecipients: ['owner@example.test'], dayOfWeek: 1, timeOfDay: '09:00', label: 'Main' })); expect(mock.db.assuranceDomain.create.mock.calls[0][0].data.nextRunAt).toEqual(new Date(2026, 8, day, 9)) })
  it('lists only subscription domains with latest scan and unresolved alert counts', async () => { mock.db.assuranceDomain.findMany.mockResolvedValue([domainData({ scans: [{ id: 's1' }], alerts: [{ id: 'a1' }] }), domainData({ id: 'd2' })]); expect(await (await domains.GET()).json()).toMatchObject({ domains: [{ latestScan: { id: 's1' }, unresolvedAlerts: 1 }, { latestScan: null, unresolvedAlerts: 0 }] }); expect(mock.db.assuranceDomain.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { subscriptionId: 'as1' } })) })
  it('protects domain-list authentication and handles internal creation/read errors', async () => { mock.auth.mockRejectedValueOnce(new Error('Authentication required')); expect((await domains.GET()).status).toBe(401); mock.db.assuranceDomain.findMany.mockRejectedValue(new Error('db failed')); expect((await domains.GET()).status).toBe(500); mock.db.assuranceDomain.create.mockRejectedValue(new Error('db failed')); expect((await domains.POST(req({ domain: 'https://example.test' }))).status).toBe(500) })
})

describe('domain ownership and settings', () => {
  const handlers = [() => domain.GET(req(), params), () => domain.PATCH(req({ label: 'New' }), params), () => domain.DELETE(req(), params)]
  it.each(handlers)('requires subscription ownership for each domain operation', async handler => { mock.subscription.mockResolvedValueOnce(null); expect((await handler()).status).toBe(403); expect((await handler()).status).toBe(404); expect(mock.db.assuranceDomain.update).not.toHaveBeenCalled(); expect(mock.db.assuranceDomain.delete).not.toHaveBeenCalled() })
  it('returns scoped domain evidence and statistics', async () => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData({ reports: [{ id: 'r1', pdfUrl: '/report' }] })); expect(await (await domain.GET(req(), params)).json()).toMatchObject({ reports: [{ id: 'r1', pdfUrl: '/report' }], statistics: { averageScore: 92 } }); expect(mock.db.assuranceDomain.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'item1', subscriptionId: 'as1' } })); expect(mock.stats).toHaveBeenCalledWith('item1') })
  it.each([{ scanFrequency: 'DAILY' }, { scoreThreshold: 80 }, { language: 'zz' }, { emailRecipients: false }, { emailRecipients: Array(6).fill('x@example.test') }, { emailRecipients: ['bad'] }, { dayOfWeek: -1 }, { dayOfWeek: 7 }, { timeOfDay: '9AM' }])('rejects invalid settings patch %j', async body => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); expect((await domain.PATCH(req(body), params)).status).toBe(400); expect(mock.db.assuranceDomain.update).not.toHaveBeenCalled() })
  it('updates supplied settings only, and can clear active state', async () => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); const body = { label: 'New', scanFrequency: 'BIWEEKLY', scoreThreshold: 90, language: 'nl', emailRecipients: ['owner@example.test'], dayOfWeek: 5, timeOfDay: '10:30', active: false }; expect((await domain.PATCH(req(body), params)).status).toBe(200); expect(mock.db.assuranceDomain.update).toHaveBeenCalledWith({ where: { id: 'item1' }, data: body }); await domain.PATCH(req({ label: 'Only label' }), params); expect(mock.db.assuranceDomain.update).toHaveBeenLastCalledWith({ where: { id: 'item1' }, data: { label: 'Only label' } }) })
  it('deletes only the verified domain', async () => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); expect((await domain.DELETE(req(), params)).status).toBe(200); expect(mock.db.assuranceDomain.delete).toHaveBeenCalledWith({ where: { id: 'item1' } }) })
  it.each(handlers)('contains domain operation failures', async handler => { mock.db.assuranceDomain.findFirst.mockRejectedValue(new Error('db failed')); expect((await handler()).status).toBe(500) })
})

describe('alerts and reports', () => {
  it('scopes filtered alerts to the subscription, with pagination and label fallback', async () => { mock.db.assuranceAlert.findMany.mockResolvedValue([alertData(), alertData({ id: 'a2', domain: { id: 'd2', domain: 'https://other.test', label: 'Second' } })]); mock.db.assuranceAlert.count.mockResolvedValue(5); const response = await listAlerts(req({}, 'GET', '?domainId=d1&resolved=false&severity=HIGH&type=SCORE_DROP&limit=2&offset=1')); expect(await response.json()).toMatchObject({ alerts: [{ domain: { name: 'https://example.test' } }, { domain: { name: 'Second' } }], pagination: { total: 5, limit: 2, offset: 1, hasMore: true } }); expect(mock.db.assuranceAlert.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { domain: { subscriptionId: 'as1' }, domainId: 'd1', resolved: false, severity: 'HIGH', type: 'SCORE_DROP' }, take: 2, skip: 1 })) })
  it('applies default pagination and handles resolved=true', async () => { expect(await (await listAlerts(req({}, 'GET'))).json()).toMatchObject({ pagination: { limit: 50, offset: 0, hasMore: false } }); await listAlerts(req({}, 'GET', '?resolved=true')); expect(mock.db.assuranceAlert.count).toHaveBeenLastCalledWith({ where: { domain: { subscriptionId: 'as1' }, resolved: true } }) })
  const alertHandlers = [() => alert.GET(req(), params), () => alert.PATCH(req({ resolved: true }), params), () => alert.DELETE(req(), params)]
  it.each(alertHandlers)('rejects alert access without subscription or owned record', async handler => { mock.subscription.mockResolvedValueOnce(null); expect((await handler()).status).toBe(403); mock.db.assuranceAlert.findFirst.mockResolvedValue(null); expect((await handler()).status).toBe(404); expect(mock.db.assuranceAlert.update).not.toHaveBeenCalled(); expect(mock.db.assuranceAlert.delete).not.toHaveBeenCalled() })
  it('returns alert details after a subscription-scoped lookup', async () => { expect(await (await alert.GET(req(), params)).json()).toMatchObject({ id: 'item1', domain: { name: 'https://example.test' } }); mock.db.assuranceAlert.findFirst.mockResolvedValue(alertData({ domain: { id: 'd1', domain: 'https://example.test', label: 'Display' } })); expect(await (await alert.GET(req(), params)).json()).toMatchObject({ domain: { name: 'Display' } }); expect(mock.db.assuranceAlert.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'item1', domain: { subscriptionId: 'as1' } } })) })
  it('requires a real boolean for resolution state', async () => { expect((await alert.PATCH(req({ resolved: 'true' }), params)).status).toBe(400); expect(mock.db.assuranceAlert.update).not.toHaveBeenCalled() })
  it.each([true, false])('records or clears resolution metadata for state %s', async resolved => { expect((await alert.PATCH(req({ resolved }), params)).status).toBe(200); expect(mock.db.assuranceAlert.update).toHaveBeenCalledWith({ where: { id: 'item1' }, data: { resolved, resolvedAt: resolved ? expect.any(Date) : null, resolvedBy: resolved ? 'u1' : null } }) })
  it('deletes only the verified alert', async () => { expect((await alert.DELETE(req(), params)).status).toBe(200); expect(mock.db.assuranceAlert.delete).toHaveBeenCalledWith({ where: { id: 'item1' } }) })
  it.each(alertHandlers)('contains alert lookup errors', async handler => { mock.db.assuranceAlert.findFirst.mockRejectedValue(new Error('db unavailable')); expect((await handler()).status).toBe(500) })
  it('scopes and filters report lists with stable pagination', async () => { mock.db.assuranceReport.findMany.mockResolvedValue([{ id: 'r1', domain: { id: 'd1', domain: 'https://example.test', label: null } }, { id: 'r2', domain: { id: 'd1', domain: 'https://example.test', label: 'Display' } }]); mock.db.assuranceReport.count.mockResolvedValue(2); expect(await (await reports.GET(req({}, 'GET', '?domainId=d1&language=nl&limit=2&offset=0'))).json()).toMatchObject({ reports: [{ domain: { name: 'https://example.test' } }, { domain: { name: 'Display' } }], pagination: { total: 2, hasMore: false } }); expect(mock.db.assuranceReport.count).toHaveBeenCalledWith({ where: { domain: { subscriptionId: 'as1' }, domainId: 'd1', language: 'nl' } }) })
  it.each([listAlerts, reports.GET])('requires a subscription for lists and handles unauthenticated/internal failures', async handler => { mock.subscription.mockResolvedValueOnce(null); expect((await handler(req({}, 'GET'))).status).toBe(403); mock.auth.mockRejectedValueOnce(new Error('Authentication required')).mockRejectedValueOnce('db unavailable'); expect((await handler(req({}, 'GET'))).status).toBe(401); expect((await handler(req({}, 'GET'))).status).toBe(500) })
  it('requires domain and scan references before report generation', async () => { expect((await reports.POST(req({}))).status).toBe(400); expect(mock.generateReport).not.toHaveBeenCalled() })
  it('checks subscription, domain ownership and scan ownership before generation', async () => { const body = { domainId: 'd1', scanId: 's1' }; mock.subscription.mockResolvedValueOnce(null); expect((await reports.POST(req(body))).status).toBe(403); expect((await reports.POST(req(body))).status).toBe(404); mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); mock.db.assuranceScan.findFirst.mockResolvedValue(null); expect((await reports.POST(req(body))).status).toBe(404); expect(mock.db.assuranceScan.findFirst).toHaveBeenCalledWith({ where: { id: 's1', domainId: 'd1' } }); expect(mock.generateReport).not.toHaveBeenCalled() })
  it.each([undefined, 'fr'])('generates reports using requested or domain-default language %s', async language => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); expect(await (await reports.POST(req({ domainId: 'd1', scanId: 's1', language }))).json()).toMatchObject({ success: true, report: { id: 'r1', score: 92 } }); expect(mock.generateReport).toHaveBeenCalledWith({ domainId: 'd1', scanId: 's1', language: language ?? 'nl' }) })
  it('returns a controlled failure when report generation fails', async () => { mock.db.assuranceDomain.findFirst.mockResolvedValue(domainData()); mock.generateReport.mockRejectedValue(new Error('render failed')); expect((await reports.POST(req({ domainId: 'd1', scanId: 's1' }))).status).toBe(500) })
})
