import { expect, it } from 'vitest'
import { calculatePrice, getPlanPricing, getDiscountPercentage, formatEuro, formatEuroFlexible, formatPriceDisplay, getDiscountBadge, getCTAText, planIncludesAssurance, getAssurancePrice, calculateTotalMonthly, formatPrice, WEBSITE_PACK_PRICES } from './pricing'
it('keeps fixed monthly and annual checkout/display amounts aligned', () => { expect(calculatePrice('PRO', 'monthly')).toBe(34.95); expect(calculatePrice('PRO', 'yearly')).toBe(349.5); expect(getPlanPricing('PRO')).toEqual({ monthly: 34.95, yearly: { total: 349.5, perMonth: 29.13, discount: 17 } }); expect(getDiscountPercentage('PRO', 'monthly')).toBe(0); expect(getDiscountPercentage('PRO', 'yearly')).toBe(17) })
it('formats sub-cent per-page prices without rounding them to zero', () => { expect(formatEuroFlexible(0.002)).toContain('0,002'); expect(formatEuroFlexible(0.002, 'en-US')).toBe('€0.002'); expect(formatEuro(34.95, 'en-US')).toBe('€34.95'); expect(formatEuro(34.95)).toContain('34,95') })
it('makes the billing period and monthly equivalent explicit', () => { expect(formatPriceDisplay('FREE', 'monthly')).toEqual({ mainPrice: 'Free', period: 'forever' }); expect(formatPriceDisplay('PRO', 'monthly', 'en-US')).toEqual({ mainPrice: '€34.95', period: '/month' }); expect(formatPriceDisplay('PRO', 'yearly', 'en-US')).toEqual({ mainPrice: '€349.50', period: '/year', subtext: '€29.13/month' }); expect(formatPrice('PRO')).toBe('€34.95/month') })
it('shows discount badges only for discounted annual plans', () => { expect(getDiscountBadge('monthly')).toBeNull(); expect(getDiscountBadge('yearly')).toBe('Save 17%'); expect(getDiscountBadge('yearly', 'PRO')).toBe('Save 17%'); expect(getDiscountBadge('yearly', 'ENTERPRISE')).toBeNull() })
it.each([['FREE', 'Start Free'], ['PRO', 'Get Pro'], ['BUSINESS', 'Get Agency'], ['PIONEER', 'Get Pioneer'], ['ENTERPRISE', 'Contact Sales']] as const)('uses plan-specific CTA for %s', (plan, cta) => expect(getCTAText('monthly', plan)).toBe(cta))
it('uses cycle-specific CTA when a tier is omitted', () => { expect(getCTAText('monthly')).toBe('Start Monthly Plan'); expect(getCTAText('yearly')).toBe('Start Annual Plan') })
it.each(['BUSINESS', 'PIONEER', 'ENTERPRISE'] as const)('does not charge twice for included assurance on %s', planKey => { expect(planIncludesAssurance(planKey)).toBe(true); expect(getAssurancePrice(planKey)).toBe(0); expect(calculateTotalMonthly({ planKey, assurance: true })).toBe(calculatePrice(planKey, 'monthly')) })
it('sums configured website and assurance additions only when requested', () => { expect(planIncludesAssurance('PRO')).toBe(false); expect(getAssurancePrice('FREE')).toBe(0); expect(calculateTotalMonthly({ planKey: 'PRO' })).toBe(34.95); expect(calculateTotalMonthly({ planKey: 'PRO', extraWebsitePack: 'EXTRA_WEBSITE_5', assurance: true })).toBe(34.95 + WEBSITE_PACK_PRICES.EXTRA_WEBSITE_5 + getAssurancePrice('PRO')) })
