import type { ReportLabels } from "./types";

export type ReportLocale = "en" | "nl" | "de" | "fr" | "es" | "pt";

type DocxCopy = {
  reportGenerated: (date: string) => string;
  scoreGrade: (score: number, grade: string) => string;
  meta: (standard: string, risk: string, readiness: string) => string;
  healthScoreExplanation: string;
  healthSummary: (domain: string, score: number, grade: string, critical: number) => string;
  noCriticalIssues: string;
  riskSummary: (risk: string, summary: string) => string;
  estimatedRemediation: (issues: number, effort: string) => string;
  coverageNote: string;
  distribution: (critical: number, serious: number, moderate: number, minor: number) => string;
  wcagStatus: (level: string, status: string, percentage?: number) => string;
  currentMaturity: (level: string) => string;
  legend: {
    prefix: string;
    pass: string;
    fail: string;
    manual: string;
    notTested: string;
  };
  testedSummary: (total: number, pass: number, fail: number, manual: number, notTested: number) => string;
  affectedCount: (count: number, effort: string, criteria: string) => string;
  automatedScan: string;
  indicatorsOnly: string;
  eaaIntro: string;
  relevantStandards: string;
  standardsBody: string;
  scanCovers: string;
  scanCoversBody: string;
  importantNote: string;
  importantNoteBody: string;
  recommendationClosing: string;
  learnMore: string;
  legalNoticeBody: string;
  generatedBy: (brand: string) => string;
  page: string;
  of: string;
};

const COPY: Record<ReportLocale, DocxCopy> = {
  en: {
    reportGenerated: (date) => `Report generated ${date}`,
    scoreGrade: (score, grade) => `Score: ${score}/100  |  Grade ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Risk: ${risk}  |  EAA 2025: ${readiness}`,
    healthScoreExplanation: "The Health Score is derived from the number and severity of detected issues, normalized by pages analyzed. A higher score indicates fewer and less severe accessibility barriers.",
    healthSummary: (domain, score, grade, critical) => `Your website ${domain} achieved a health score of ${score}/100 (Grade ${grade}). ${critical > 0 ? `There are ${critical} critical issues requiring immediate attention.` : "No critical issues were detected."}`,
    noCriticalIssues: "No critical issues were detected.",
    riskSummary: (risk, summary) => `${risk} Risk: ${summary}`,
    estimatedRemediation: (issues, effort) => `Based on ${issues} identified issues, the estimated developer effort is ${effort}.`,
    coverageNote: "Automated testing does not cover all WCAG requirements. Manual review is recommended.",
    distribution: (c, s, m, n) => `Critical: ${c}  |  Serious: ${s}  |  Moderate: ${m}  |  Minor: ${n}`,
    wcagStatus: (level, status, percentage) => `${level}: ${status}${percentage == null ? "" : ` (${percentage}%)`}`,
    currentMaturity: (level) => `Current level: ${level}`,
    legend: { prefix: "Legend:", pass: "No violations detected", fail: "Automated violations detected", manual: "Cannot be fully verified automatically", notTested: "Outside scan scope" },
    testedSummary: (total, pass, fail, manual, notTested) => `Tested against ${total} WCAG 2.2 success criteria. ${pass} Pass, ${fail} Fail, ${manual} Need Manual Review, ${notTested} Not Tested.`,
    affectedCount: (count, effort, criteria) => `${count} element(s) affected  |  Est. ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Automated scan",
    indicatorsOnly: "Indicators only; not a conformity assessment.",
    eaaIntro: "The European Accessibility Act (EAA) sets accessibility requirements for digital products and services in the EU. Web content is commonly assessed against EN 301 549 and WCAG Level AA.",
    relevantStandards: "Relevant standards",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "What this scan covers",
    scanCoversBody: "Automated detection of common issues involving contrast, keyboard navigation, form labels, images and alternative text, structure, headings, and more.",
    importantNote: "Important note",
    importantNoteBody: "This automated scan provides indicators of potential accessibility barriers. It is not a full manual audit, legal compliance certification, or complete conformity assessment.",
    recommendationClosing: "Use these results as a starting point for remediation and ongoing monitoring. Combine them with manual testing and expert review.",
    learnMore: "Learn more about the European Accessibility Act",
    legalNoticeBody: "Enforcement timelines and obligations vary by EU member state, sector, and product type. This report is not legal advice.",
    generatedBy: (brand) => `Generated by ${brand}`,
    page: "Page",
    of: "of",
  },
  nl: {
    reportGenerated: (date) => `Rapport gegenereerd op ${date}`,
    scoreGrade: (score, grade) => `Score: ${score}/100  |  Scoreklasse ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Risico: ${risk}  |  EAA 2025: ${readiness}`,
    healthScoreExplanation: "De gezondheidsscore is gebaseerd op het aantal en de ernst van gedetecteerde problemen, genormaliseerd naar het aantal geanalyseerde pagina's. Een hogere score wijst op minder en minder ernstige toegankelijkheidsdrempels.",
    healthSummary: (domain, score, grade, critical) => `Website ${domain} behaalde een gezondheidsscore van ${score}/100 (scoreklasse ${grade}). ${critical > 0 ? `Er zijn ${critical} kritieke problemen die directe aandacht vereisen.` : "Er zijn geen kritieke problemen gedetecteerd."}`,
    noCriticalIssues: "Er zijn geen kritieke problemen gedetecteerd.",
    riskSummary: (risk, summary) => `${risk} risico: ${summary}`,
    estimatedRemediation: (issues, effort) => `Op basis van ${issues} gevonden problemen bedraagt de geschatte ontwikkelinspanning ${effort}.`,
    coverageNote: "Geautomatiseerde tests dekken niet alle WCAG-eisen. Handmatige beoordeling wordt aanbevolen.",
    distribution: (c, s, m, n) => `Kritiek: ${c}  |  Ernstig: ${s}  |  Matig: ${m}  |  Klein: ${n}`,
    wcagStatus: (level, status, percentage) => `${level}: ${status}${percentage == null ? "" : ` (${percentage}%)`}`,
    currentMaturity: (level) => `Huidig niveau: ${level}`,
    legend: { prefix: "Legenda:", pass: "Geen overtredingen gedetecteerd", fail: "Geautomatiseerde overtredingen gedetecteerd", manual: "Niet volledig automatisch te controleren", notTested: "Buiten de scope van de scan" },
    testedSummary: (total, pass, fail, manual, notTested) => `Getest tegen ${total} WCAG 2.2-succescriteria. ${pass} geslaagd, ${fail} mislukt, ${manual} vereisen handmatige review en ${notTested} zijn niet getest.`,
    affectedCount: (count, effort, criteria) => `${count} element(en) getroffen  |  Geschat ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Geautomatiseerde scan",
    indicatorsOnly: "Alleen indicatoren; geen conformiteitsbeoordeling.",
    eaaIntro: "De European Accessibility Act (EAA) stelt toegankelijkheidseisen aan digitale producten en diensten in de EU. Webcontent wordt doorgaans beoordeeld aan de hand van EN 301 549 en WCAG niveau AA.",
    relevantStandards: "Relevante standaarden",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "Wat deze scan controleert",
    scanCoversBody: "Geautomatiseerde detectie van veelvoorkomende problemen met contrast, toetsenbordnavigatie, formulierlabels, afbeeldingen en alternatieve tekst, structuur, koppen en meer.",
    importantNote: "Belangrijke opmerking",
    importantNoteBody: "Deze geautomatiseerde scan geeft indicatoren van mogelijke toegankelijkheidsdrempels. Het is geen volledige handmatige audit, juridische compliancecertificering of complete conformiteitsbeoordeling.",
    recommendationClosing: "Gebruik deze resultaten als startpunt voor herstel en doorlopende monitoring. Combineer ze met handmatige tests en beoordeling door een expert.",
    learnMore: "Meer informatie over de European Accessibility Act",
    legalNoticeBody: "Handhavingstermijnen en verplichtingen verschillen per EU-lidstaat, sector en producttype. Dit rapport is geen juridisch advies.",
    generatedBy: (brand) => `Gegenereerd door ${brand}`,
    page: "Pagina",
    of: "van",
  },
  de: {
    reportGenerated: (date) => `Bericht erstellt am ${date}`,
    scoreGrade: (score, grade) => `Score: ${score}/100  |  Note ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Risiko: ${risk}  |  EAA 2025: ${readiness}`,
    healthScoreExplanation: "Der Health-Score basiert auf Anzahl und Schweregrad der erkannten Probleme, normalisiert nach analysierten Seiten. Ein hoher Wert weist auf weniger und weniger schwere Barrieren hin.",
    healthSummary: (domain, score, grade, critical) => `Die Website ${domain} erreichte einen Health-Score von ${score}/100 (Note ${grade}). ${critical > 0 ? `${critical} kritische Probleme erfordern sofortige Aufmerksamkeit.` : "Es wurden keine kritischen Probleme erkannt."}`,
    noCriticalIssues: "Es wurden keine kritischen Probleme erkannt.",
    riskSummary: (risk, summary) => `Risiko: ${risk}. ${summary}`,
    estimatedRemediation: (issues, effort) => `Für die ${issues} erkannten Probleme wird ein Entwicklungsaufwand von ${effort} geschätzt.`,
    coverageNote: "Automatisierte Tests decken nicht alle WCAG-Anforderungen ab. Eine manuelle Prüfung wird empfohlen.",
    distribution: (c, s, m, n) => `Kritisch: ${c}  |  Schwerwiegend: ${s}  |  Mittel: ${m}  |  Gering: ${n}`,
    wcagStatus: (level, status, percentage) => `${level}: ${status}${percentage == null ? "" : ` (${percentage}%)`}`,
    currentMaturity: (level) => `Aktuelles Niveau: ${level}`,
    legend: { prefix: "Legende:", pass: "Keine Verstöße erkannt", fail: "Automatisierte Verstöße erkannt", manual: "Nicht vollständig automatisiert prüfbar", notTested: "Außerhalb des Scanbereichs" },
    testedSummary: (total, pass, fail, manual, notTested) => `Gegen ${total} WCAG 2.2-Erfolgskriterien getestet. ${pass} bestanden, ${fail} nicht bestanden, ${manual} manuell zu prüfen, ${notTested} nicht getestet.`,
    affectedCount: (count, effort, criteria) => `${count} Element(e) betroffen  |  Gesch. ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Automatisierter Scan",
    indicatorsOnly: "Nur Indikatoren; keine Konformitätsbewertung.",
    eaaIntro: "Der European Accessibility Act (EAA) legt Barrierefreiheitsanforderungen für digitale Produkte und Dienste in der EU fest. Webinhalte werden üblicherweise anhand EN 301 549 und WCAG Level AA bewertet.",
    relevantStandards: "Relevante Standards",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "Was dieser Scan abdeckt",
    scanCoversBody: "Automatisierte Erkennung häufiger Probleme bei Kontrast, Tastaturnavigation, Formularbeschriftungen, Bildern und Alternativtexten, Struktur, Überschriften und mehr.",
    importantNote: "Wichtiger Hinweis",
    importantNoteBody: "Dieser automatisierte Scan liefert Hinweise auf mögliche Barrieren. Er ist kein vollständiges manuelles Audit, keine rechtliche Compliance-Zertifizierung und keine vollständige Konformitätsbewertung.",
    recommendationClosing: "Nutzen Sie die Ergebnisse als Ausgangspunkt für Behebung und laufende Überwachung. Ergänzen Sie sie durch manuelle Tests und fachliche Prüfung.",
    learnMore: "Mehr über den European Accessibility Act",
    legalNoticeBody: "Fristen und Pflichten unterscheiden sich je nach EU-Mitgliedstaat, Branche und Produkttyp. Dieser Bericht ist keine Rechtsberatung.",
    generatedBy: (brand) => `Erstellt von ${brand}`,
    page: "Seite",
    of: "von",
  },
  fr: {
    reportGenerated: (date) => `Rapport généré le ${date}`,
    scoreGrade: (score, grade) => `Score : ${score}/100  |  Note ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Risque : ${risk}  |  EAA 2025 : ${readiness}`,
    healthScoreExplanation: "Le score de santé est calculé à partir du nombre et de la gravité des problèmes détectés, normalisés selon les pages analysées. Un score élevé indique moins d'obstacles et des obstacles moins graves.",
    healthSummary: (domain, score, grade, critical) => `Le site ${domain} a obtenu un score de santé de ${score}/100 (note ${grade}). ${critical > 0 ? `${critical} problèmes critiques nécessitent une attention immédiate.` : "Aucun problème critique n'a été détecté."}`,
    noCriticalIssues: "Aucun problème critique n'a été détecté.",
    riskSummary: (risk, summary) => `Risque ${risk} : ${summary}`,
    estimatedRemediation: (issues, effort) => `Pour les ${issues} problèmes identifiés, l'effort de développement estimé est de ${effort}.`,
    coverageNote: "Les tests automatisés ne couvrent pas toutes les exigences WCAG. Une revue manuelle est recommandée.",
    distribution: (c, s, m, n) => `Critique : ${c}  |  Sérieux : ${s}  |  Modéré : ${m}  |  Mineur : ${n}`,
    wcagStatus: (level, status, percentage) => `${level} : ${status}${percentage == null ? "" : ` (${percentage} %)`}`,
    currentMaturity: (level) => `Niveau actuel : ${level}`,
    legend: { prefix: "Légende :", pass: "Aucune violation détectée", fail: "Violations automatisées détectées", manual: "Vérification automatique complète impossible", notTested: "Hors du périmètre du scan" },
    testedSummary: (total, pass, fail, manual, notTested) => `Test effectué sur ${total} critères de succès WCAG 2.2. ${pass} réussis, ${fail} échoués, ${manual} à revoir manuellement et ${notTested} non testés.`,
    affectedCount: (count, effort, criteria) => `${count} élément(s) affecté(s)  |  Est. ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Scan automatisé",
    indicatorsOnly: "Indicateurs uniquement ; pas une évaluation de conformité.",
    eaaIntro: "L'European Accessibility Act (EAA) fixe des exigences d'accessibilité pour les produits et services numériques dans l'UE. Les contenus web sont généralement évalués selon EN 301 549 et WCAG niveau AA.",
    relevantStandards: "Normes pertinentes",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "Ce que couvre ce scan",
    scanCoversBody: "Détection automatisée des problèmes courants liés au contraste, à la navigation au clavier, aux libellés de formulaires, aux images et textes alternatifs, à la structure, aux titres, etc.",
    importantNote: "Remarque importante",
    importantNoteBody: "Ce scan automatisé fournit des indicateurs d'obstacles potentiels. Il ne constitue ni un audit manuel complet, ni une certification juridique, ni une évaluation complète de conformité.",
    recommendationClosing: "Utilisez ces résultats comme point de départ pour la correction et le suivi continu. Complétez-les par des tests manuels et une revue experte.",
    learnMore: "En savoir plus sur l'European Accessibility Act",
    legalNoticeBody: "Les calendriers et obligations varient selon l'État membre, le secteur et le type de produit. Ce rapport ne constitue pas un avis juridique.",
    generatedBy: (brand) => `Généré par ${brand}`,
    page: "Page",
    of: "sur",
  },
  es: {
    reportGenerated: (date) => `Informe generado el ${date}`,
    scoreGrade: (score, grade) => `Puntuación: ${score}/100  |  Calificación ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Riesgo: ${risk}  |  EAA 2025: ${readiness}`,
    healthScoreExplanation: "La puntuación de salud se calcula a partir del número y la gravedad de los problemas detectados, normalizados por las páginas analizadas. Una puntuación alta indica menos barreras y de menor gravedad.",
    healthSummary: (domain, score, grade, critical) => `El sitio ${domain} obtuvo una puntuación de salud de ${score}/100 (calificación ${grade}). ${critical > 0 ? `Hay ${critical} problemas críticos que requieren atención inmediata.` : "No se detectaron problemas críticos."}`,
    noCriticalIssues: "No se detectaron problemas críticos.",
    riskSummary: (risk, summary) => `Riesgo ${risk}: ${summary}`,
    estimatedRemediation: (issues, effort) => `Para los ${issues} problemas identificados, el esfuerzo de desarrollo estimado es ${effort}.`,
    coverageNote: "Las pruebas automatizadas no cubren todos los requisitos WCAG. Se recomienda una revisión manual.",
    distribution: (c, s, m, n) => `Crítico: ${c}  |  Grave: ${s}  |  Moderado: ${m}  |  Menor: ${n}`,
    wcagStatus: (level, status, percentage) => `${level}: ${status}${percentage == null ? "" : ` (${percentage} %)`}`,
    currentMaturity: (level) => `Nivel actual: ${level}`,
    legend: { prefix: "Leyenda:", pass: "No se detectaron infracciones", fail: "Se detectaron infracciones automatizadas", manual: "No puede verificarse por completo automáticamente", notTested: "Fuera del alcance del escaneo" },
    testedSummary: (total, pass, fail, manual, notTested) => `Probado contra ${total} criterios de éxito WCAG 2.2. ${pass} aprobados, ${fail} fallidos, ${manual} requieren revisión manual y ${notTested} no probados.`,
    affectedCount: (count, effort, criteria) => `${count} elemento(s) afectado(s)  |  Est. ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Escaneo automatizado",
    indicatorsOnly: "Solo indicadores; no es una evaluación de conformidad.",
    eaaIntro: "La European Accessibility Act (EAA) establece requisitos de accesibilidad para productos y servicios digitales en la UE. El contenido web suele evaluarse según EN 301 549 y WCAG nivel AA.",
    relevantStandards: "Normas relevantes",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "Qué cubre este escaneo",
    scanCoversBody: "Detección automatizada de problemas habituales de contraste, navegación por teclado, etiquetas de formulario, imágenes y texto alternativo, estructura, encabezados y más.",
    importantNote: "Nota importante",
    importantNoteBody: "Este escaneo automatizado proporciona indicadores de posibles barreras. No es una auditoría manual completa, una certificación legal ni una evaluación completa de conformidad.",
    recommendationClosing: "Utilice los resultados como punto de partida para la corrección y la monitorización continua. Combínelos con pruebas manuales y revisión experta.",
    learnMore: "Más información sobre la European Accessibility Act",
    legalNoticeBody: "Los plazos y obligaciones varían según el Estado miembro, el sector y el tipo de producto. Este informe no constituye asesoramiento jurídico.",
    generatedBy: (brand) => `Generado por ${brand}`,
    page: "Página",
    of: "de",
  },
  pt: {
    reportGenerated: (date) => `Relatório gerado em ${date}`,
    scoreGrade: (score, grade) => `Pontuação: ${score}/100  |  Classificação ${grade}`,
    meta: (standard, risk, readiness) => `${standard}  |  Risco: ${risk}  |  EAA 2025: ${readiness}`,
    healthScoreExplanation: "A pontuação de saúde é calculada a partir do número e da gravidade dos problemas detetados, normalizados pelas páginas analisadas. Uma pontuação elevada indica menos barreiras e de menor gravidade.",
    healthSummary: (domain, score, grade, critical) => `O site ${domain} obteve uma pontuação de saúde de ${score}/100 (classificação ${grade}). ${critical > 0 ? `Existem ${critical} problemas críticos que exigem atenção imediata.` : "Não foram detetados problemas críticos."}`,
    noCriticalIssues: "Não foram detetados problemas críticos.",
    riskSummary: (risk, summary) => `Risco ${risk}: ${summary}`,
    estimatedRemediation: (issues, effort) => `Para os ${issues} problemas identificados, o esforço de desenvolvimento estimado é ${effort}.`,
    coverageNote: "Os testes automatizados não cobrem todos os requisitos WCAG. Recomenda-se uma revisão manual.",
    distribution: (c, s, m, n) => `Crítico: ${c}  |  Grave: ${s}  |  Moderado: ${m}  |  Menor: ${n}`,
    wcagStatus: (level, status, percentage) => `${level}: ${status}${percentage == null ? "" : ` (${percentage}%)`}`,
    currentMaturity: (level) => `Nível atual: ${level}`,
    legend: { prefix: "Legenda:", pass: "Nenhuma violação detetada", fail: "Violações automatizadas detetadas", manual: "Não pode ser totalmente verificado automaticamente", notTested: "Fora do âmbito do scan" },
    testedSummary: (total, pass, fail, manual, notTested) => `Testado contra ${total} critérios de sucesso WCAG 2.2. ${pass} aprovados, ${fail} reprovados, ${manual} requerem revisão manual e ${notTested} não testados.`,
    affectedCount: (count, effort, criteria) => `${count} elemento(s) afetado(s)  |  Est. ${effort}${criteria ? `  |  ${criteria}` : ""}`,
    automatedScan: "Scan automatizado",
    indicatorsOnly: "Apenas indicadores; não é uma avaliação de conformidade.",
    eaaIntro: "O European Accessibility Act (EAA) estabelece requisitos de acessibilidade para produtos e serviços digitais na UE. O conteúdo web é geralmente avaliado segundo a EN 301 549 e as WCAG nível AA.",
    relevantStandards: "Normas relevantes",
    standardsBody: "WCAG 2.1 AA + EN 301 549",
    scanCovers: "O que este scan abrange",
    scanCoversBody: "Deteção automatizada de problemas comuns de contraste, navegação por teclado, etiquetas de formulários, imagens e texto alternativo, estrutura, cabeçalhos e mais.",
    importantNote: "Nota importante",
    importantNoteBody: "Este scan automatizado fornece indicadores de possíveis barreiras. Não é uma auditoria manual completa, certificação jurídica ou avaliação completa de conformidade.",
    recommendationClosing: "Utilize os resultados como ponto de partida para correção e monitorização contínua. Combine-os com testes manuais e revisão especializada.",
    learnMore: "Saiba mais sobre o European Accessibility Act",
    legalNoticeBody: "Os prazos e as obrigações variam por Estado-Membro, setor e tipo de produto. Este relatório não constitui aconselhamento jurídico.",
    generatedBy: (brand) => `Gerado por ${brand}`,
    page: "Página",
    of: "de",
  },
};

export function getDocxCopy(locale: string): DocxCopy {
  return COPY[(locale.split("-")[0] as ReportLocale)] || COPY.en;
}

export function localizeSeverity(labels: ReportLabels, severity: string): string {
  return labels[severity as "critical" | "serious" | "moderate" | "minor"] || severity;
}

export function localizeWcagStatus(labels: ReportLabels, status: string): string {
  if (status === "Pass" || status === "pass") return labels.statusPass;
  if (status === "Fail" || status === "fail") return labels.statusFail;
  if (status === "Partial" || status === "partial") return labels.statusPartial;
  if (status === "Needs Manual Review") return labels.statusNeedsManualReview;
  if (status === "Not Tested") return labels.statusNotTested;
  return status;
}

export function localizeMaturity(labels: ReportLabels, level: string): string {
  if (level === "Basic") return labels.maturityBasic;
  if (level === "Structured") return labels.maturityStructured;
  if (level === "Proactive") return labels.maturityProactive;
  if (level === "Continuous") return labels.maturityContinuous;
  return level;
}

export function localizeRiskLevel(locale: string, risk: string): string {
  const levels: Record<ReportLocale, Record<string, string>> = {
    en: { Low: "Low", Moderate: "Moderate", High: "High", Critical: "Critical" },
    nl: { Low: "Laag", Moderate: "Matig", High: "Hoog", Critical: "Kritiek" },
    de: { Low: "Niedrig", Moderate: "Mittel", High: "Hoch", Critical: "Kritisch" },
    fr: { Low: "Faible", Moderate: "Modéré", High: "Élevé", Critical: "Critique" },
    es: { Low: "Bajo", Moderate: "Moderado", High: "Alto", Critical: "Crítico" },
    pt: { Low: "Baixo", Moderate: "Moderado", High: "Alto", Critical: "Crítico" },
  };
  const resolved = (locale.split("-")[0] as ReportLocale) in levels
    ? (locale.split("-")[0] as ReportLocale)
    : "en";
  return levels[resolved][risk] || risk;
}

export function localizeRating(labels: ReportLabels, rating: string): string {
  if (rating === "Excellent") return labels.ratingExcellent;
  if (rating === "Good") return labels.ratingGood;
  if (rating === "Fair") return labels.ratingFair;
  if (rating === "Needs Work") return labels.ratingNeedsWork;
  if (rating === "Poor") return labels.ratingPoor;
  return rating;
}

export function formatReportDate(value: string | Date, locale: string): string {
  const dateLocales: Record<ReportLocale, string> = {
    en: "en-GB",
    nl: "nl-NL",
    de: "de-DE",
    fr: "fr-FR",
    es: "es-ES",
    pt: "pt-PT",
  };
  const resolved = (locale.split("-")[0] as ReportLocale) in dateLocales
    ? (locale.split("-")[0] as ReportLocale)
    : "en";
  try {
    return new Intl.DateTimeFormat(dateLocales[resolved], {
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(new Date(value));
  } catch {
    return String(value);
  }
}
