import { beforeEach, afterEach, expect, it, vi } from 'vitest'
let mode: typeof import('./display-mode')
beforeEach(async () => { vi.resetModules(); mode = await import('./display-mode') })
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks() })
it('keeps SSR defaults and in-memory updates without browser APIs', () => { expect(mode.getPriceDisplayMode()).toBe('excl'); expect(mode.getPricingCountry()).toBe('NL'); mode.setPriceDisplayMode('incl'); mode.setPricingCountry('DE'); expect(mode.getPriceDisplayMode()).toBe('incl'); expect(mode.getPricingCountry()).toBe('DE') })
it('notifies subscribers and honors unsubscribe', () => { const listener = vi.fn(); const countries = vi.fn(); const stopMode = mode.onPriceDisplayModeChange(listener); const stopCountry = mode.onPricingCountryChange(countries); mode.setPriceDisplayMode('incl'); mode.setPricingCountry('DE'); expect(listener).toHaveBeenCalledWith('incl'); expect(countries).toHaveBeenCalledWith('DE'); stopMode(); stopCountry(); mode.setPriceDisplayMode('excl'); mode.setPricingCountry('NL'); expect(listener).toHaveBeenCalledOnce(); expect(countries).toHaveBeenCalledOnce() })
it('loads valid stored preferences, falls back on invalid values and persists changes', () => { const store = new Map<string, string>(); vi.stubGlobal('window', {}); vi.stubGlobal('localStorage', { getItem: (key: string) => store.get(key), setItem: (key: string, value: string) => store.set(key, value) }); expect(mode.getPriceDisplayMode()).toBe('excl'); expect(mode.getPricingCountry()).toBe('NL'); store.set('vexnexa_price_display_mode', 'invalid'); expect(mode.getPriceDisplayMode()).toBe('excl'); mode.setPriceDisplayMode('incl'); mode.setPricingCountry('FR'); expect(mode.getPriceDisplayMode()).toBe('incl'); expect(mode.getPricingCountry()).toBe('FR'); mode.setPriceDisplayMode('excl'); expect(mode.getPriceDisplayMode()).toBe('excl') })
it('survives unavailable local storage without throwing', () => { vi.stubGlobal('window', {}); vi.stubGlobal('localStorage', { getItem: () => { throw new Error('blocked') }, setItem: () => { throw new Error('blocked') } }); expect(mode.getPriceDisplayMode()).toBe('excl'); expect(mode.getPricingCountry()).toBe('NL'); expect(() => mode.setPriceDisplayMode('incl')).not.toThrow(); expect(() => mode.setPricingCountry('DE')).not.toThrow() })
it('syncs only the display preference and treats offline sync as non-fatal', async () => { const fetch = vi.fn().mockResolvedValue({ ok: true }); vi.stubGlobal('fetch', fetch); await mode.syncDisplayModeToProfile('incl'); expect(fetch).toHaveBeenCalledWith('/api/user/preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ priceDisplayMode: 'incl' }) }); fetch.mockRejectedValue(new Error('offline')); await expect(mode.syncDisplayModeToProfile('excl')).resolves.toBeUndefined() })
