/**
 * ISO-3166 alpha-2 country list for billing profiles.
 *
 * Each entry has:
 *  - code: ISO 3166-1 alpha-2
 *  - name: English display name
 *  - eu:   true if current EU member state
 */

export interface Country {
  code: string;
  name: string;
  eu: boolean;
}

/** EU member state codes (2024) */
export const EU_COUNTRY_CODES = new Set([
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR",
  "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL",
  "PL", "PT", "RO", "SK", "SI", "ES", "SE",
]);

export function isEuCountry(code: string): boolean {
  return EU_COUNTRY_CODES.has(code.toUpperCase());
}

export function isNlCountry(code: string): boolean {
  return code.toUpperCase() === "NL";
}

/**
 * Complete ISO-3166 alpha-2 country list (249 entries).
 * Sorted alphabetically by name.
 */
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", eu: false },
  { code: "AX", name: "Åland Islands", eu: false },
  { code: "AL", name: "Albania", eu: false },
  { code: "DZ", name: "Algeria", eu: false },
  { code: "AS", name: "American Samoa", eu: false },
  { code: "AD", name: "Andorra", eu: false },
  { code: "AO", name: "Angola", eu: false },
  { code: "AI", name: "Anguilla", eu: false },
  { code: "AQ", name: "Antarctica", eu: false },
  { code: "AG", name: "Antigua and Barbuda", eu: false },
  { code: "AR", name: "Argentina", eu: false },
  { code: "AM", name: "Armenia", eu: false },
  { code: "AW", name: "Aruba", eu: false },
  { code: "AU", name: "Australia", eu: false },
  { code: "AT", name: "Austria", eu: true },
  { code: "AZ", name: "Azerbaijan", eu: false },
  { code: "BS", name: "Bahamas", eu: false },
  { code: "BH", name: "Bahrain", eu: false },
  { code: "BD", name: "Bangladesh", eu: false },
  { code: "BB", name: "Barbados", eu: false },
  { code: "BY", name: "Belarus", eu: false },
  { code: "BE", name: "Belgium", eu: true },
  { code: "BZ", name: "Belize", eu: false },
  { code: "BJ", name: "Benin", eu: false },
  { code: "BM", name: "Bermuda", eu: false },
  { code: "BT", name: "Bhutan", eu: false },
  { code: "BO", name: "Bolivia", eu: false },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", eu: false },
  { code: "BA", name: "Bosnia and Herzegovina", eu: false },
  { code: "BW", name: "Botswana", eu: false },
  { code: "BV", name: "Bouvet Island", eu: false },
  { code: "BR", name: "Brazil", eu: false },
  { code: "IO", name: "British Indian Ocean Territory", eu: false },
  { code: "BN", name: "Brunei Darussalam", eu: false },
  { code: "BG", name: "Bulgaria", eu: true },
  { code: "BF", name: "Burkina Faso", eu: false },
  { code: "BI", name: "Burundi", eu: false },
  { code: "CV", name: "Cabo Verde", eu: false },
  { code: "KH", name: "Cambodia", eu: false },
  { code: "CM", name: "Cameroon", eu: false },
  { code: "CA", name: "Canada", eu: false },
  { code: "KY", name: "Cayman Islands", eu: false },
  { code: "CF", name: "Central African Republic", eu: false },
  { code: "TD", name: "Chad", eu: false },
  { code: "CL", name: "Chile", eu: false },
  { code: "CN", name: "China", eu: false },
  { code: "CX", name: "Christmas Island", eu: false },
  { code: "CC", name: "Cocos (Keeling) Islands", eu: false },
  { code: "CO", name: "Colombia", eu: false },
  { code: "KM", name: "Comoros", eu: false },
  { code: "CG", name: "Congo", eu: false },
  { code: "CD", name: "Congo, Democratic Republic of the", eu: false },
  { code: "CK", name: "Cook Islands", eu: false },
  { code: "CR", name: "Costa Rica", eu: false },
  { code: "CI", name: "Côte d'Ivoire", eu: false },
  { code: "HR", name: "Croatia", eu: true },
  { code: "CU", name: "Cuba", eu: false },
  { code: "CW", name: "Curaçao", eu: false },
  { code: "CY", name: "Cyprus", eu: true },
  { code: "CZ", name: "Czechia", eu: true },
  { code: "DK", name: "Denmark", eu: true },
  { code: "DJ", name: "Djibouti", eu: false },
  { code: "DM", name: "Dominica", eu: false },
  { code: "DO", name: "Dominican Republic", eu: false },
  { code: "EC", name: "Ecuador", eu: false },
  { code: "EG", name: "Egypt", eu: false },
  { code: "SV", name: "El Salvador", eu: false },
  { code: "GQ", name: "Equatorial Guinea", eu: false },
  { code: "ER", name: "Eritrea", eu: false },
  { code: "EE", name: "Estonia", eu: true },
  { code: "SZ", name: "Eswatini", eu: false },
  { code: "ET", name: "Ethiopia", eu: false },
  { code: "FK", name: "Falkland Islands", eu: false },
  { code: "FO", name: "Faroe Islands", eu: false },
  { code: "FJ", name: "Fiji", eu: false },
  { code: "FI", name: "Finland", eu: true },
  { code: "FR", name: "France", eu: true },
  { code: "GF", name: "French Guiana", eu: false },
  { code: "PF", name: "French Polynesia", eu: false },
  { code: "TF", name: "French Southern Territories", eu: false },
  { code: "GA", name: "Gabon", eu: false },
  { code: "GM", name: "Gambia", eu: false },
  { code: "GE", name: "Georgia", eu: false },
  { code: "DE", name: "Germany", eu: true },
  { code: "GH", name: "Ghana", eu: false },
  { code: "GI", name: "Gibraltar", eu: false },
  { code: "GR", name: "Greece", eu: true },
  { code: "GL", name: "Greenland", eu: false },
  { code: "GD", name: "Grenada", eu: false },
  { code: "GP", name: "Guadeloupe", eu: false },
  { code: "GU", name: "Guam", eu: false },
  { code: "GT", name: "Guatemala", eu: false },
  { code: "GG", name: "Guernsey", eu: false },
  { code: "GN", name: "Guinea", eu: false },
  { code: "GW", name: "Guinea-Bissau", eu: false },
  { code: "GY", name: "Guyana", eu: false },
  { code: "HT", name: "Haiti", eu: false },
  { code: "HM", name: "Heard Island and McDonald Islands", eu: false },
  { code: "VA", name: "Holy See", eu: false },
  { code: "HN", name: "Honduras", eu: false },
  { code: "HK", name: "Hong Kong", eu: false },
  { code: "HU", name: "Hungary", eu: true },
  { code: "IS", name: "Iceland", eu: false },
  { code: "IN", name: "India", eu: false },
  { code: "ID", name: "Indonesia", eu: false },
  { code: "IR", name: "Iran", eu: false },
  { code: "IQ", name: "Iraq", eu: false },
  { code: "IE", name: "Ireland", eu: true },
  { code: "IM", name: "Isle of Man", eu: false },
  { code: "IL", name: "Israel", eu: false },
  { code: "IT", name: "Italy", eu: true },
  { code: "JM", name: "Jamaica", eu: false },
  { code: "JP", name: "Japan", eu: false },
  { code: "JE", name: "Jersey", eu: false },
  { code: "JO", name: "Jordan", eu: false },
  { code: "KZ", name: "Kazakhstan", eu: false },
  { code: "KE", name: "Kenya", eu: false },
  { code: "KI", name: "Kiribati", eu: false },
  { code: "KP", name: "Korea, Democratic People's Republic of", eu: false },
  { code: "KR", name: "Korea, Republic of", eu: false },
  { code: "KW", name: "Kuwait", eu: false },
  { code: "KG", name: "Kyrgyzstan", eu: false },
  { code: "LA", name: "Lao People's Democratic Republic", eu: false },
  { code: "LV", name: "Latvia", eu: true },
  { code: "LB", name: "Lebanon", eu: false },
  { code: "LS", name: "Lesotho", eu: false },
  { code: "LR", name: "Liberia", eu: false },
  { code: "LY", name: "Libya", eu: false },
  { code: "LI", name: "Liechtenstein", eu: false },
  { code: "LT", name: "Lithuania", eu: true },
  { code: "LU", name: "Luxembourg", eu: true },
  { code: "MO", name: "Macao", eu: false },
  { code: "MG", name: "Madagascar", eu: false },
  { code: "MW", name: "Malawi", eu: false },
  { code: "MY", name: "Malaysia", eu: false },
  { code: "MV", name: "Maldives", eu: false },
  { code: "ML", name: "Mali", eu: false },
  { code: "MT", name: "Malta", eu: true },
  { code: "MH", name: "Marshall Islands", eu: false },
  { code: "MQ", name: "Martinique", eu: false },
  { code: "MR", name: "Mauritania", eu: false },
  { code: "MU", name: "Mauritius", eu: false },
  { code: "YT", name: "Mayotte", eu: false },
  { code: "MX", name: "Mexico", eu: false },
  { code: "FM", name: "Micronesia", eu: false },
  { code: "MD", name: "Moldova", eu: false },
  { code: "MC", name: "Monaco", eu: false },
  { code: "MN", name: "Mongolia", eu: false },
  { code: "ME", name: "Montenegro", eu: false },
  { code: "MS", name: "Montserrat", eu: false },
  { code: "MA", name: "Morocco", eu: false },
  { code: "MZ", name: "Mozambique", eu: false },
  { code: "MM", name: "Myanmar", eu: false },
  { code: "NA", name: "Namibia", eu: false },
  { code: "NR", name: "Nauru", eu: false },
  { code: "NP", name: "Nepal", eu: false },
  { code: "NL", name: "Netherlands", eu: true },
  { code: "NC", name: "New Caledonia", eu: false },
  { code: "NZ", name: "New Zealand", eu: false },
  { code: "NI", name: "Nicaragua", eu: false },
  { code: "NE", name: "Niger", eu: false },
  { code: "NG", name: "Nigeria", eu: false },
  { code: "NU", name: "Niue", eu: false },
  { code: "NF", name: "Norfolk Island", eu: false },
  { code: "MK", name: "North Macedonia", eu: false },
  { code: "MP", name: "Northern Mariana Islands", eu: false },
  { code: "NO", name: "Norway", eu: false },
  { code: "OM", name: "Oman", eu: false },
  { code: "PK", name: "Pakistan", eu: false },
  { code: "PW", name: "Palau", eu: false },
  { code: "PS", name: "Palestine, State of", eu: false },
  { code: "PA", name: "Panama", eu: false },
  { code: "PG", name: "Papua New Guinea", eu: false },
  { code: "PY", name: "Paraguay", eu: false },
  { code: "PE", name: "Peru", eu: false },
  { code: "PH", name: "Philippines", eu: false },
  { code: "PN", name: "Pitcairn", eu: false },
  { code: "PL", name: "Poland", eu: true },
  { code: "PT", name: "Portugal", eu: true },
  { code: "PR", name: "Puerto Rico", eu: false },
  { code: "QA", name: "Qatar", eu: false },
  { code: "RE", name: "Réunion", eu: false },
  { code: "RO", name: "Romania", eu: true },
  { code: "RU", name: "Russian Federation", eu: false },
  { code: "RW", name: "Rwanda", eu: false },
  { code: "BL", name: "Saint Barthélemy", eu: false },
  { code: "SH", name: "Saint Helena", eu: false },
  { code: "KN", name: "Saint Kitts and Nevis", eu: false },
  { code: "LC", name: "Saint Lucia", eu: false },
  { code: "MF", name: "Saint Martin (French part)", eu: false },
  { code: "PM", name: "Saint Pierre and Miquelon", eu: false },
  { code: "VC", name: "Saint Vincent and the Grenadines", eu: false },
  { code: "WS", name: "Samoa", eu: false },
  { code: "SM", name: "San Marino", eu: false },
  { code: "ST", name: "Sao Tome and Principe", eu: false },
  { code: "SA", name: "Saudi Arabia", eu: false },
  { code: "SN", name: "Senegal", eu: false },
  { code: "RS", name: "Serbia", eu: false },
  { code: "SC", name: "Seychelles", eu: false },
  { code: "SL", name: "Sierra Leone", eu: false },
  { code: "SG", name: "Singapore", eu: false },
  { code: "SX", name: "Sint Maarten (Dutch part)", eu: false },
  { code: "SK", name: "Slovakia", eu: true },
  { code: "SI", name: "Slovenia", eu: true },
  { code: "SB", name: "Solomon Islands", eu: false },
  { code: "SO", name: "Somalia", eu: false },
  { code: "ZA", name: "South Africa", eu: false },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", eu: false },
  { code: "SS", name: "South Sudan", eu: false },
  { code: "ES", name: "Spain", eu: true },
  { code: "LK", name: "Sri Lanka", eu: false },
  { code: "SD", name: "Sudan", eu: false },
  { code: "SR", name: "Suriname", eu: false },
  { code: "SJ", name: "Svalbard and Jan Mayen", eu: false },
  { code: "SE", name: "Sweden", eu: true },
  { code: "CH", name: "Switzerland", eu: false },
  { code: "SY", name: "Syrian Arab Republic", eu: false },
  { code: "TW", name: "Taiwan", eu: false },
  { code: "TJ", name: "Tajikistan", eu: false },
  { code: "TZ", name: "Tanzania", eu: false },
  { code: "TH", name: "Thailand", eu: false },
  { code: "TL", name: "Timor-Leste", eu: false },
  { code: "TG", name: "Togo", eu: false },
  { code: "TK", name: "Tokelau", eu: false },
  { code: "TO", name: "Tonga", eu: false },
  { code: "TT", name: "Trinidad and Tobago", eu: false },
  { code: "TN", name: "Tunisia", eu: false },
  { code: "TR", name: "Turkey", eu: false },
  { code: "TM", name: "Turkmenistan", eu: false },
  { code: "TC", name: "Turks and Caicos Islands", eu: false },
  { code: "TV", name: "Tuvalu", eu: false },
  { code: "UG", name: "Uganda", eu: false },
  { code: "UA", name: "Ukraine", eu: false },
  { code: "AE", name: "United Arab Emirates", eu: false },
  { code: "GB", name: "United Kingdom", eu: false },
  { code: "US", name: "United States", eu: false },
  { code: "UM", name: "United States Minor Outlying Islands", eu: false },
  { code: "UY", name: "Uruguay", eu: false },
  { code: "UZ", name: "Uzbekistan", eu: false },
  { code: "VU", name: "Vanuatu", eu: false },
  { code: "VE", name: "Venezuela", eu: false },
  { code: "VN", name: "Viet Nam", eu: false },
  { code: "VG", name: "Virgin Islands (British)", eu: false },
  { code: "VI", name: "Virgin Islands (U.S.)", eu: false },
  { code: "WF", name: "Wallis and Futuna", eu: false },
  { code: "EH", name: "Western Sahara", eu: false },
  { code: "YE", name: "Yemen", eu: false },
  { code: "ZM", name: "Zambia", eu: false },
  { code: "ZW", name: "Zimbabwe", eu: false },
];

/** Lookup country by code */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}

/** Get country name by code */
export function getCountryName(code: string): string {
  return getCountryByCode(code)?.name ?? code;
}
