import { beforeEach, afterEach, expect, it, vi } from 'vitest'
const mock = vi.hoisted(() => ({ payments: vi.fn(), subscriptions: vi.fn() }))
vi.mock('@/lib/mollie', () => ({ getMollieClient: () => ({ payments: { page: mock.payments }, subscription: { page: mock.subscriptions } }) }))
import { getMollieRevenue, getSubscriptionBreakdown, getMollieDashboardUrl } from './mollie-analytics'
const paid = (value: string) => ({ status: 'paid', amount: { value } })
beforeEach(() => { vi.resetAllMocks(); vi.spyOn(console, 'error').mockImplementation(() => {}); mock.payments.mockResolvedValue([]); mock.subscriptions.mockResolvedValue([]) })
afterEach(() => vi.restoreAllMocks())
it('sums only paid revenue and calculates relative growth', async () => { mock.payments.mockResolvedValueOnce([paid('30.00'), paid('20.00'), { status: 'failed', amount: { value: '1000' } }, { status: 'paid' }]).mockResolvedValueOnce([paid('25.00')]).mockResolvedValueOnce([paid('150.00')]); mock.subscriptions.mockResolvedValue([{ status: 'active' }, { status: 'canceled' }]); expect(await getMollieRevenue(new Date('2026-08-01Z'), new Date('2026-09-01Z'))).toMatchObject({ totalRevenue: 150, periodRevenue: 50, previousPeriodRevenue: 25, revenueGrowth: 100, activeSubscriptions: 1, payments: [paid('30.00'), paid('20.00'), { status: 'paid' }] }) })
it('uses 100% growth for the first revenue period and zero for empty responses', async () => { mock.payments.mockResolvedValueOnce([paid('10')]).mockResolvedValueOnce(null).mockResolvedValueOnce(null); mock.subscriptions.mockResolvedValue(null); expect(await getMollieRevenue(new Date('2026-08-01Z'), new Date('2026-09-01Z'))).toMatchObject({ revenueGrowth: 100, activeSubscriptions: 0 }); expect(await getMollieRevenue(new Date('2026-08-01Z'), new Date('2026-09-01Z'))).toMatchObject({ revenueGrowth: 0, totalRevenue: 0, periodRevenue: 0 }) })
it('returns safe empty analytics if the provider fails', async () => { mock.payments.mockRejectedValue(new Error('offline')); expect(await getMollieRevenue(new Date('2026-08-01Z'), new Date('2026-09-01Z'))).toEqual({ totalRevenue: 0, periodRevenue: 0, previousPeriodRevenue: 0, revenueGrowth: 0, payments: [], activeSubscriptions: 0 }) })
it('groups active subscription amounts while ignoring missing amounts and canceled subscriptions', async () => { mock.subscriptions.mockResolvedValue([{ status: 'active', description: 'Pro', amount: { value: '34.95' } }, { status: 'active', description: 'Pro', amount: { value: '34.95' } }, { status: 'active', amount: { value: '15' } }, { status: 'active' }, { status: 'canceled', amount: { value: '999' } }]); expect(await getSubscriptionBreakdown()).toEqual({ Pro: { count: 2, monthlyRevenue: 69.9 }, Unknown: { count: 1, monthlyRevenue: 15 } }) })
it('returns an empty breakdown for absent responses or provider failure', async () => { mock.subscriptions.mockResolvedValueOnce(null).mockRejectedValueOnce(new Error('offline')); expect(await getSubscriptionBreakdown()).toEqual({}); expect(await getSubscriptionBreakdown()).toEqual({}) })
it('links supported dashboard sections and falls back for unknown sections', () => { expect(getMollieDashboardUrl()).toBe('https://www.mollie.com/dashboard'); expect(getMollieDashboardUrl('payments')).toBe('https://www.mollie.com/dashboard/payments'); expect(getMollieDashboardUrl('unknown')).toBe('https://www.mollie.com/dashboard') })
