import { beforeEach, afterEach, expect, it, vi } from 'vitest'
const mock = vi.hoisted(() => ({
  db: { checkoutQuote: { create: vi.fn() }, billingProfile: { findUnique: vi.fn() }, assuranceSubscription: { findFirst: vi.fn(), findUnique: vi.fn(), update: vi.fn(), upsert: vi.fn() } },
  mollie: { customers: { get: vi.fn() }, payments: { create: vi.fn(), get: vi.fn() }, customerSubscriptions: { create: vi.fn(), cancel: vi.fn() } },
  customer: vi.fn(), invoice: vi.fn(), testMode: vi.fn(),
}))
vi.mock('../prisma', () => ({ prisma: mock.db }))
vi.mock('@mollie/api-client', () => ({ SequenceType: { first: 'first' } }))
vi.mock('../mollie', () => ({ mollie: mock.mollie, appUrl: (path: string) => `https://app.example.test${path}`, formatMollieAmount: (n: number) => n.toFixed(2), isMollieTestMode: mock.testMode }))
vi.mock('../billing/mollie-flows', () => ({ createOrGetMollieCustomer: mock.customer }))
vi.mock('@/lib/billing/invoice-service', () => ({ sendInvoiceForPayment: mock.invoice }))
import { createAssuranceCheckoutPayment, createAssuranceSubscription, cancelAssuranceSubscription, changeAssuranceTier, processAssuranceWebhookPayment, getActiveAssuranceSubscription, hasActiveAssuranceSubscription } from './billing'
const record = (overrides = {}) => ({ id: 'as1', userId: 'u1', tier: 'BASIC', mollieSubscriptionId: 'sub1', user: { mollieCustomerId: 'c1' }, ...overrides })
const payment = (overrides = {}) => ({ id: 'tr1', status: 'paid', customerId: 'c1', metadata: { product: 'assurance', userId: 'u1', tier: 'BASIC' }, getCheckoutUrl: () => 'https://checkout.example.test/tr1', ...overrides })
beforeEach(() => {
  vi.resetAllMocks(); vi.spyOn(console, 'log').mockImplementation(() => {}); vi.spyOn(console, 'warn').mockImplementation(() => {}); vi.spyOn(console, 'error').mockImplementation(() => {})
  mock.customer.mockResolvedValue({ id: 'c1' }); mock.mollie.customers.get.mockResolvedValue({ id: 'c1' }); mock.mollie.payments.create.mockResolvedValue(payment()); mock.mollie.payments.get.mockResolvedValue(payment()); mock.mollie.customerSubscriptions.create.mockResolvedValue({ id: 'sub1' }); mock.db.billingProfile.findUnique.mockResolvedValue(null); mock.db.assuranceSubscription.findFirst.mockResolvedValue(null); mock.db.assuranceSubscription.findUnique.mockResolvedValue(record()); mock.db.assuranceSubscription.upsert.mockResolvedValue(record()); mock.db.assuranceSubscription.update.mockResolvedValue(record())
})
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); vi.unstubAllEnvs() })

it('charges the displayed gross price without applying VAT twice', async () => {
  expect(await createAssuranceCheckoutPayment({ userId: 'u1', email: 'user@example.test', tier: 'BASIC' })).toMatchObject({ id: 'tr1' })
  expect(mock.customer).toHaveBeenCalledWith('u1', 'user@example.test'); expect(mock.mollie.payments.create).toHaveBeenCalledWith(expect.objectContaining({ amount: { currency: 'EUR', value: '9.99' }, sequenceType: 'first', metadata: expect.objectContaining({ userId: 'u1', tier: 'BASIC', netAmount: '8.26', vatAmount: '1.73', countryCode: 'NL' }) }))
  expect(mock.db.checkoutQuote.create).toHaveBeenCalledWith({ data: expect.objectContaining({ totalAmount: 9.99, baseAmount: 8.26, vatAmount: 1.73, molliePaymentId: 'tr1' }) })
})
it.each([['EU_REVERSE_CHARGE', 'reverse_charge'], ['NON_EU_NO_VAT', 'no_tax']] as const)('stores %s invoice breakdown without changing total', async (regime, taxMode) => {
  mock.testMode.mockReturnValue(true); await createAssuranceCheckoutPayment({ userId: 'u1', email: 'user@example.test', tier: 'PRO', billingCycle: 'annual', mollieCustomerId: 'c1', countryCode: 'DE', vatId: 'DE123456789', taxDecision: { regime, vatRate: 0, invoiceNote: 'test note' } })
  expect(mock.customer).not.toHaveBeenCalled(); expect(mock.mollie.customers.get).toHaveBeenCalledWith('c1'); expect(mock.mollie.payments.create.mock.calls[0][0].amount.value).toBe('254.99'); expect(mock.mollie.payments.create.mock.calls[0][0]).not.toHaveProperty('method'); expect(mock.mollie.payments.create.mock.calls[0][0]).not.toHaveProperty('locale')
  expect(mock.db.checkoutQuote.create).toHaveBeenCalledWith({ data: expect.objectContaining({ baseAmount: 254.99, vatAmount: 0, taxMode, vatId: 'DE123456789' }) })
})
it('returns created payment when storing the optional quote fails', async () => { mock.db.checkoutQuote.create.mockRejectedValue(new Error('db offline')); expect(await createAssuranceCheckoutPayment({ userId: 'u1', email: 'user@example.test', tier: 'BASIC' })).toMatchObject({ id: 'tr1' }) })
it('propagates payment provider errors without creating a quote', async () => { mock.mollie.payments.create.mockRejectedValue(new Error('checkout unavailable')); await expect(createAssuranceCheckoutPayment({ userId: 'u1', email: 'user@example.test', tier: 'BASIC' })).rejects.toThrow('checkout unavailable'); expect(mock.db.checkoutQuote.create).not.toHaveBeenCalled() })
it.each([['monthly', '1 month', '9.99'], ['semiannual', '6 months', '55.99'], ['annual', '12 months', '101.99']] as const)('creates correct %s recurring interval and amount', async (billingCycle, interval, amount) => {
  await createAssuranceSubscription({ userId: 'u1', tier: 'BASIC', mollieCustomerId: 'c1', billingCycle })
  expect(mock.mollie.customerSubscriptions.create).toHaveBeenCalledWith(expect.objectContaining({ customerId: 'c1', interval, amount: { currency: 'EUR', value: amount } })); expect(mock.db.assuranceSubscription.upsert).toHaveBeenCalledWith(expect.objectContaining({ create: expect.objectContaining({ userId: 'u1', status: 'active', totalPrice: Number(amount), billingCycle, vatRate: 0.21 }), update: expect.objectContaining({ canceledAt: null, expiresAt: null }) }))
})
it('derives recurring invoice tax from persisted customer billing profile', async () => { mock.db.billingProfile.findUnique.mockResolvedValue({ countryCode: 'DE', billingType: 'business', vatValid: true, vatId: 'DE123' }); await createAssuranceSubscription({ userId: 'u1', tier: 'PRO', mollieCustomerId: 'c1' }); expect(mock.db.assuranceSubscription.upsert).toHaveBeenCalledWith(expect.objectContaining({ create: expect.objectContaining({ totalPrice: 24.99, vatRate: 0, taxRegime: 'EU_REVERSE_CHARGE', countryCode: 'DE', vatId: 'DE123' }) })) })
it('replaces an existing subscription using its stable local ID', async () => { mock.db.assuranceSubscription.findFirst.mockResolvedValue(record({ mollieSubscriptionId: 'old' })); await createAssuranceSubscription({ userId: 'u1', tier: 'PRO', mollieCustomerId: 'c1', countryCode: 'BE', vatId: 'BE123' }); expect(mock.mollie.customerSubscriptions.cancel).toHaveBeenCalledWith('old', { customerId: 'c1' }); expect(mock.db.assuranceSubscription.upsert).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'as1' } })) })
it('does not create local paid entitlements when provider creation fails', async () => { mock.mollie.customerSubscriptions.create.mockRejectedValue(new Error('provider offline')); await expect(createAssuranceSubscription({ userId: 'u1', tier: 'BASIC', mollieCustomerId: 'c1' })).rejects.toThrow('provider offline'); expect(mock.db.assuranceSubscription.upsert).not.toHaveBeenCalled() })
it('rejects cancellation of a missing subscription', async () => { mock.db.assuranceSubscription.findUnique.mockResolvedValue(null); await expect(cancelAssuranceSubscription('missing')).rejects.toThrow('Subscription not found'); expect(mock.mollie.customerSubscriptions.cancel).not.toHaveBeenCalled() })
it('cancels billing and sets an exact seven-day local grace period', async () => { vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-06T12:00:00Z')); await cancelAssuranceSubscription('as1'); expect(mock.mollie.customerSubscriptions.cancel).toHaveBeenCalledWith('sub1', { customerId: 'c1' }); expect(mock.db.assuranceSubscription.update).toHaveBeenCalledWith({ where: { id: 'as1' }, data: { status: 'canceled', canceledAt: new Date('2026-09-06T12:00:00Z'), expiresAt: new Date('2026-09-13T12:00:00Z') } }) })
it('handles a local-only subscription without making a provider cancellation', async () => { mock.db.assuranceSubscription.findUnique.mockResolvedValue(record({ mollieSubscriptionId: null })); await cancelAssuranceSubscription('as1'); expect(mock.mollie.customerSubscriptions.cancel).not.toHaveBeenCalled(); expect(mock.db.assuranceSubscription.update).toHaveBeenCalledOnce() })
it.each([null, record({ user: { mollieCustomerId: null } })])('rejects tier changes without subscription/customer identity', async subscription => { mock.db.assuranceSubscription.findUnique.mockResolvedValue(subscription); await expect(changeAssuranceTier({ subscriptionId: 'as1', newTier: 'PRO' })).rejects.toThrow(); expect(mock.mollie.customerSubscriptions.create).not.toHaveBeenCalled() })
it('changes to the requested tier and annual billing cycle', async () => { await changeAssuranceTier({ subscriptionId: 'as1', newTier: 'PRO', billingCycle: 'annual' }); expect(mock.mollie.customerSubscriptions.cancel).toHaveBeenCalledWith('sub1', { customerId: 'c1' }); expect(mock.mollie.customerSubscriptions.create).toHaveBeenCalledWith(expect.objectContaining({ amount: { currency: 'EUR', value: '254.99' }, interval: '12 months' })) })
it('can set a tier for a local subscription without an existing provider ID', async () => { mock.db.assuranceSubscription.findUnique.mockResolvedValue(record({ mollieSubscriptionId: null })); await changeAssuranceTier({ subscriptionId: 'as1', newTier: 'PRO' }); expect(mock.mollie.customerSubscriptions.cancel).not.toHaveBeenCalled(); expect(mock.mollie.customerSubscriptions.create).toHaveBeenCalledOnce() })
it.each(['open', 'pending', 'failed', 'canceled'])('does not create assurance access for %s payments', async status => { mock.mollie.payments.get.mockResolvedValue(payment({ status })); expect(await processAssuranceWebhookPayment('tr1')).toBeNull(); expect(mock.db.assuranceSubscription.findFirst).not.toHaveBeenCalled() })
it.each([{}, { userId: 'u1' }, { userId: 'u1', tier: 'BASIC', product: 'other' }])('ignores incomplete or wrong-product metadata', async metadata => { mock.mollie.payments.get.mockResolvedValue(payment({ metadata })); expect(await processAssuranceWebhookPayment('tr1')).toBeNull(); expect(mock.mollie.customerSubscriptions.create).not.toHaveBeenCalled() })
it('does not create duplicate active subscriptions on webhook retries', async () => { mock.db.assuranceSubscription.findFirst.mockResolvedValue(record()); expect(await processAssuranceWebhookPayment('tr1')).toMatchObject({ id: 'as1' }); expect(mock.mollie.customerSubscriptions.create).not.toHaveBeenCalled(); expect(mock.invoice).not.toHaveBeenCalled() })
it('creates a subscription from fetched paid metadata and sends its invoice', async () => { mock.mollie.payments.get.mockResolvedValue(payment({ metadata: { product: 'assurance', userId: 'u1', tier: 'PRO', billingCycle: 'annual' } })); expect(await processAssuranceWebhookPayment('tr1')).toMatchObject({ id: 'as1' }); expect(mock.mollie.payments.get).toHaveBeenCalledWith('tr1'); expect(mock.mollie.customerSubscriptions.create).toHaveBeenCalledWith(expect.objectContaining({ amount: { currency: 'EUR', value: '254.99' } })); expect(mock.invoice).toHaveBeenCalledWith('tr1') })
it('keeps successful subscription activation when the invoice service throws', async () => { mock.invoice.mockRejectedValue(new Error('mail failed')); expect(await processAssuranceWebhookPayment('tr1')).toMatchObject({ id: 'as1' }) })
it('propagates provider fetch failures for webhook retry', async () => { mock.mollie.payments.get.mockRejectedValue(new Error('network unavailable')); await expect(processAssuranceWebhookPayment('tr1')).rejects.toThrow('network unavailable') })
it('looks up only this customer’s active/past-due subscription and active domains', async () => {
  expect(await hasActiveAssuranceSubscription('u1')).toBe(false); mock.db.assuranceSubscription.findFirst.mockResolvedValue(record()); expect(await hasActiveAssuranceSubscription('u1')).toBe(true); await getActiveAssuranceSubscription('u1')
  expect(mock.db.assuranceSubscription.findFirst).toHaveBeenCalledWith({ where: { userId: 'u1', status: { in: ['active', 'past_due'] } }, include: { domains: { where: { active: true }, orderBy: { createdAt: 'desc' } } } })
})
