import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { lookupKvk } from './kvkLookup'
const fetchMock = vi.fn()
beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal('fetch', fetchMock); vi.stubEnv('KVK_API_KEY', 'fake-unit-test-key'); vi.spyOn(console, 'warn').mockImplementation(() => {}); fetchMock.mockRejectedValue(new Error('unmocked network prohibited')) })
afterEach(() => { vi.unstubAllGlobals(); vi.unstubAllEnvs(); vi.restoreAllMocks() })
it('does not invoke the service without API configuration or a valid eight-digit identifier', async () => { vi.stubEnv('KVK_API_KEY', ''); expect(await lookupKvk('12345678')).toEqual({ found: false }); vi.stubEnv('KVK_API_KEY', 'fake-unit-test-key'); expect(await lookupKvk('123')).toEqual({ found: false }); expect(fetchMock).not.toHaveBeenCalled() })
it('prefers the main visiting address and normalizes identifier punctuation', async () => { fetchMock.mockResolvedValue(new Response(JSON.stringify({ naam: 'Example BV', _embedded: { hoofdvestiging: { adressen: [{ type: 'postadres', straatnaam: 'Postal', huisnummer: 9 }, { type: 'bezoekadres', straatnaam: 'Main', huisnummer: 1, huisnummertoevoeging: 'A', plaats: 'Amsterdam', postcode: '1234AB' }] } } }))); expect(await lookupKvk('12 34-56.78')).toEqual({ found: true, companyName: 'Example BV', street: 'Main 1 A', city: 'Amsterdam', postalCode: '1234AB', kvkNumber: '12345678' }); expect(fetchMock).toHaveBeenCalledWith('https://api.kvk.nl/api/v1/basisprofielen/12345678', expect.objectContaining({ method: 'GET', headers: { apikey: 'fake-unit-test-key', Accept: 'application/json' }, signal: expect.any(AbortSignal) })) })
it.each([{ handelsnaam: 'Trade Name' }, { _embedded: { hoofdvestiging: { naam: 'Embedded Name' } } }, {}])('handles alternate name fields and absent addresses', async data => { fetchMock.mockResolvedValue(new Response(JSON.stringify(data))); const result = await lookupKvk('12345678'); expect(result.found).toBe(true); expect(result.companyName).toBe('handelsnaam' in data ? 'Trade Name' : '_embedded' in data ? 'Embedded Name' : undefined); expect(result.street).toBeUndefined() })
it('uses a top-level first address when no visiting address exists', async () => { fetchMock.mockResolvedValue(new Response(JSON.stringify({ adressen: [{ type: 'postadres', straatnaam: 'Postal', huisnummer: 9, plaats: 'Town' }] }))); expect(await lookupKvk('12345678')).toMatchObject({ street: 'Postal 9', city: 'Town', postalCode: undefined }) })
it.each([{ adressen: [] }, { adressen: [{}] }, { adressen: 'malformed' }])('tolerates absent or malformed address details', async data => { fetchMock.mockResolvedValue(new Response(JSON.stringify(data))); expect(await lookupKvk('12345678')).toMatchObject({ found: true, street: undefined, city: undefined }) })
it.each([404, 503])('degrades gracefully on provider HTTP %i', async status => { fetchMock.mockResolvedValue(new Response('failed', { status })); expect(await lookupKvk('12345678')).toEqual({ found: false }) })
it.each([new Error('network down'), 'network down'])('contains thrown network errors', async error => { fetchMock.mockRejectedValue(error); expect(await lookupKvk('12345678')).toEqual({ found: false }) })
