import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { NextRequest } from 'next/server'
const mock = vi.hoisted(() => ({ auth: vi.fn(), upsert: vi.fn(), lookup: vi.fn(), fetch: vi.fn() }))
vi.mock('@/lib/supabase/server-new', () => ({ createClient: async () => ({ auth: { getUser: mock.auth } }) }))
vi.mock('@/lib/prisma', () => ({ prisma: { billingProfile: { upsert: mock.upsert } } }))
vi.mock('@/lib/company/kvkLookup', () => ({ lookupKvk: mock.lookup }))
import { POST as vat } from './validate-vat/route'
import { POST as kvk } from './kvk-lookup/route'
const req = (body: unknown) => new NextRequest('https://app.example.test/api/billing/validation', { method: 'POST', body: JSON.stringify(body) })
beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal('fetch', mock.fetch); mock.fetch.mockRejectedValue(new Error('Unmocked network prohibited')); mock.auth.mockResolvedValue({ data: { user: { id: 'u1' } }, error: null }); vi.spyOn(console, 'warn').mockImplementation(() => {}); vi.spyOn(console, 'error').mockImplementation(() => {}) })
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks() })
it.each([vat, kvk])('requires a valid user session before external validation', async handler => { mock.auth.mockResolvedValueOnce({ data: { user: null }, error: null }).mockResolvedValueOnce({ data: { user: { id: 'u1' } }, error: { message: 'expired' } }); expect((await handler(req({}))).status).toBe(401); expect((await handler(req({}))).status).toBe(401); expect(mock.fetch).not.toHaveBeenCalled(); expect(mock.lookup).not.toHaveBeenCalled() })
it.each([{}, { countryCode: 'NL' }, { vatId: 'NL123456789B01' }])('requires VAT country and identifier %j', async body => { expect((await vat(req(body))).status).toBe(400); expect(mock.fetch).not.toHaveBeenCalled() })
it.each([{ countryCode: 'US', vatId: 'US123456' }, { countryCode: 'NL', vatId: 'invalid' }])('rejects non-EU or malformed VAT before network', async body => { expect(await (await vat(req(body))).json()).toMatchObject({ valid: false, error: expect.any(String) }); expect(mock.fetch).not.toHaveBeenCalled(); expect(mock.upsert).not.toHaveBeenCalled() })
it('normalizes VAT, strips prefix for VIES and records positive evidence for authenticated owner', async () => {
  mock.fetch.mockResolvedValue(new Response(JSON.stringify({ valid: true, name: '  Example   BV ', address: '  Street\n1 ' }), { status: 200 }))
  const response = await vat(req({ countryCode: 'nl', vatId: 'nl123.456.789-b01', userId: 'other' })); expect(await response.json()).toMatchObject({ valid: true, vatId: 'NL123456789B01', countryCode: 'NL', companyName: 'Example BV', address: 'Street 1' })
  expect(mock.fetch).toHaveBeenCalledWith(expect.stringContaining('/rest-api/'), expect.objectContaining({ method: 'POST', body: JSON.stringify({ countryCode: 'NL', vatNumber: '123456789B01' }), signal: expect.any(AbortSignal) })); expect(mock.upsert).toHaveBeenCalledWith(expect.objectContaining({ where: { userId: 'u1' }, update: expect.objectContaining({ vatValid: true, companyName: 'Example BV', vatCheckedAt: expect.any(Date) }) }))
})
it.each([undefined, '', '---', '-', '   '])('does not persist unavailable VIES names %s', async name => { mock.fetch.mockResolvedValue(new Response(JSON.stringify({ valid: false, name, address: name }))); expect(await (await vat(req({ countryCode: 'DE', vatId: 'DE123456789' }))).json()).toMatchObject({ valid: false, companyName: null, address: null }); expect(mock.upsert.mock.calls[0][0].update).not.toHaveProperty('companyName') })
it('falls back to SOAP when VIES REST is unavailable', async () => {
  mock.fetch.mockResolvedValueOnce(new Response('Unavailable', { status: 503 })).mockResolvedValueOnce(new Response('<valid>true</valid><name>Example BV</name><address>Street 1</address>'))
  expect(await (await vat(req({ countryCode: 'NL', vatId: 'NL123456789B01' }))).json()).toMatchObject({ valid: true, companyName: 'Example BV' }); expect(mock.fetch).toHaveBeenNthCalledWith(2, expect.stringContaining('checkVatService'), expect.objectContaining({ headers: { 'Content-Type': 'text/xml; charset=utf-8', SOAPAction: '' }, body: expect.stringContaining('<urn:vatNumber>123456789B01</urn:vatNumber>') }))
})
it('handles a negative SOAP response with missing company information', async () => { mock.fetch.mockRejectedValueOnce(new Error('REST down')).mockResolvedValueOnce(new Response('<valid>false</valid>')); expect(await (await vat(req({ countryCode: 'DE', vatId: 'DE123456789' }))).json()).toMatchObject({ valid: false, companyName: null, address: null }) })
it.each([new Response('<Fault>Down</Fault>'), 'network failed'])('returns warning and does not mark VAT valid when both providers fail', async failure => { mock.fetch.mockRejectedValueOnce(new Error('REST down')); if (failure instanceof Response) mock.fetch.mockResolvedValueOnce(failure); else mock.fetch.mockRejectedValueOnce(failure); const result = await (await vat(req({ countryCode: 'DE', vatId: 'DE123456789' }))).json(); expect(result).toMatchObject({ valid: false, warning: expect.stringContaining('VIES unavailable:') }); expect(mock.upsert.mock.calls[0][0].update.vatValid).toBe(false) })
it('returns controlled errors for malformed VAT field types and failed persistence', async () => { expect((await vat(req({ countryCode: 123, vatId: 'NL123456789B01' }))).status).toBe(500); mock.fetch.mockResolvedValue(new Response(JSON.stringify({ valid: true }))); mock.upsert.mockRejectedValue(new Error('db down')); expect((await vat(req({ countryCode: 'NL', vatId: 'NL123456789B01' }))).status).toBe(500) })
it.each([{}, { kvkNumber: '123' }, { kvkNumber: '123456789' }])('rejects malformed KVK numbers %j', async body => { expect((await kvk(req(body))).status).toBe(400); expect(mock.lookup).not.toHaveBeenCalled() })
it('normalizes KVK punctuation and returns the verified lookup result', async () => { mock.lookup.mockResolvedValue({ found: true, name: 'Example BV' }); expect(await (await kvk(req({ kvkNumber: '12 34-56.78' }))).json()).toEqual({ found: true, name: 'Example BV' }); expect(mock.lookup).toHaveBeenCalledWith('12345678') })
it('contains KVK lookup failures without exposing internals', async () => { mock.lookup.mockRejectedValue(new Error('provider secret detail')); expect(await (await kvk(req({ kvkNumber: '12345678' }))).json()).toEqual({ found: false, error: 'Internal server error' }) })
