import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { prisma } from '@/lib/prisma'
import { errorResponse, unauthorizedResponse, forbiddenResponse } from '@/lib/api-response'
import { isAdmin } from '@/lib/admin'

/**
 * GET /api/admin/export-report - Export admin analytics report (CSV or PDF)
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user }, error: authError } = await supabase.auth.getUser()

    if (authError || !user) {
      return unauthorizedResponse()
    }

    if (!await isAdmin(user.id)) {
      return forbiddenResponse('Admin access required')
    }

    const { searchParams } = new URL(request.url)
    const format = searchParams.get('format') || 'csv'
    const reportType = searchParams.get('type') || 'overview'

    // Gather report data
    const now = new Date()
    const last30Days = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)
    const last7Days = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

    const [
      totalUsers,
      activeUsers,
      totalSites,
      totalScans,
      recentUsers,
      recentScans,
      planDistribution,
    ] = await Promise.all([
      prisma.user.count(),
      prisma.user.count({ where: { updatedAt: { gte: last30Days } } }),
      prisma.site.count(),
      prisma.scan.count(),
      prisma.user.count({ where: { createdAt: { gte: last30Days } } }),
      prisma.scan.count({ where: { createdAt: { gte: last7Days } } }),
      prisma.user.groupBy({
        by: ['plan'],
        _count: true,
      }),
    ])

    const reportData = {
      generatedAt: now.toISOString(),
      generatedBy: user.email,
      period: '30 days',
      summary: {
        totalUsers,
        activeUsers,
        totalSites,
        totalScans,
        newUsersLast30Days: recentUsers,
        scansLast7Days: recentScans,
      },
      planDistribution: planDistribution.map(p => ({
        plan: p.plan,
        count: p._count,
      })),
    }

    if (format === 'csv') {
      // Generate CSV
      const csv = generateCSV(reportData)

      return new Response(csv, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="admin-report-${now.toISOString().split('T')[0]}.csv"`,
        },
      })
    } else if (format === 'json') {
      return new Response(JSON.stringify(reportData, null, 2), {
        headers: {
          'Content-Type': 'application/json',
          'Content-Disposition': `attachment; filename="admin-report-${now.toISOString().split('T')[0]}.json"`,
        },
      })
    } else {
      return errorResponse('Invalid format. Supported: csv, json', 400)
    }
  } catch (error) {
    console.error('Error exporting report:', error)
    return errorResponse('Failed to export report', 500)
  }
}

function generateCSV(data: any): string {
  const lines: string[] = []

  // Header
  lines.push('Tutusporta Admin Report')
  lines.push(`Generated At,${data.generatedAt}`)
  lines.push(`Generated By,${data.generatedBy}`)
  lines.push(`Period,${data.period}`)
  lines.push('')

  // Summary Section
  lines.push('Summary')
  lines.push('Metric,Value')
  lines.push(`Total Users,${data.summary.totalUsers}`)
  lines.push(`Active Users (30d),${data.summary.activeUsers}`)
  lines.push(`Total Sites,${data.summary.totalSites}`)
  lines.push(`Total Scans,${data.summary.totalScans}`)
  lines.push(`New Users (30d),${data.summary.newUsersLast30Days}`)
  lines.push(`Scans (7d),${data.summary.scansLast7Days}`)
  lines.push('')

  // Plan Distribution
  lines.push('Plan Distribution')
  lines.push('Plan,User Count')
  data.planDistribution.forEach((item: any) => {
    lines.push(`${item.plan},${item.count}`)
  })

  return lines.join('\n')
}
